/** Types And Functions declarations for DSL
 * This file is auto generated by utils/gen_def.ts
 * Do not edit this file directly.
 *
 * @version 1.0.2
 * @date Fri Nov 21 2025 01:46:14 GMT+0800 (中国标准时间)
 * @author Aluria
 */

export { };

class TypeBase {
}

type SysAllTypes = int | float | bool | str | Int | Float | Bool | Str | Vec | GUID | Entity | Prefab | Faction | ConfigId | List | Dict | Struct;
type SysItemTypes = Entity | GUID | Int | Bool | Float | Str | int | bool | float | str | Faction | Vec | ConfigId | Prefab;
type SysKeyTypes = Entity | GUID | Int | Str | int | str | Faction | ConfigId | Prefab;
type SysValTypes = Entity | GUID | Int | Bool | Float | Str | int | bool | float | str | Faction | Vec | ConfigId | Prefab | List;
declare global {
  namespace Self {
    const Self = global.Self;
  }
  namespace Node {
    const Self = global.Node;
  }
  namespace Local {
    const Self = global.Local;
  }
  namespace Signal {
    const Self = global.Signal;
  }
  namespace Timer {
    const Self = global.Timer;
  }
  
  // ====== System Basic Types ======
  type int = bigint;
  type float = number;
  type bool = boolean;
  type str = string;
  class Float extends TypeBase {
    type: "Float";
    val: number;
    toString(): str;
    private clone(): Float;
  }

  class Bool extends TypeBase {
    type: "Bool";
    val: boolean;
    toString(): str;
    private clone(): Bool;
  }

  class Str extends TypeBase {
    type: "Str";
    val: string;
    toString(): str;
    private clone(): Str;
  }

  class Vec extends TypeBase {
    type: "Vec";
    val: [number, number, number];
    get x(): number;
    get y(): number;
    get z(): number;
    get 0(): number;
    get 1(): number;
    get 2(): number;
    toString(): str;
    private clone(): Vec;
  }

  class Int extends TypeBase {
    type: "Int";
    val: bigint;
    toString(): str;
    private clone(): Int;
  }

  class GUID extends TypeBase {
    type: "GUID";
    val: bigint;
    toString(): str;
    private clone(): GUID;
  }

  class Entity extends TypeBase {
    type: "Entity";
    val: bigint;
    toString(): str;
    private clone(): Entity;
  }

  class Prefab extends TypeBase {
    type: "Prefab";
    val: bigint;
    toString(): str;
    private clone(): Prefab;
  }

  class Faction extends TypeBase {
    type: "Faction";
    val: bigint;
    toString(): str;
    private clone(): Faction;
  }

  class ConfigId extends TypeBase {
    type: "ConfigId";
    val: bigint;
    toString(): str;
    private clone(): ConfigId;
  }

  class List extends TypeBase {
    type: "List";
    val: SysItemTypes[];
    val_type: "Entity" | "GUID" | "Int" | "Bool" | "Float" | "Str" | "Faction" | "Vec" | "ConfigId" | "Prefab";
    [index: number]: SysItemTypes;
    toString(): str;
    private clone(): List;
  }

  class Dict extends TypeBase {
    type: "Dict";
    key: SysKeyTypes[];
    val: SysValTypes[];
    key_type: "Entity" | "GUID" | "Int" | "Str" | "Faction" | "ConfigId" | "Prefab";
    val_type: "Entity" | "GUID" | "Int" | "Bool" | "Float" | "Str" | "Faction" | "Vec" | "ConfigId" | "Prefab" | "List";
    toString(): str;
    private clone(): Dict;
  }

  class Struct extends TypeBase {
    type: "Struct";
    fields: string[];
    val: SysValTypes[];
    val_type: "int" | "float" | "bool" | "str" | "Int" | "Float" | "Bool" | "Str" | "Vec" | "GUID" | "Entity" | "Prefab" | "Faction" | "ConfigId" | "List" | "Dict" | "Struct";
    toString(): str;
    private clone(): Struct;
  }

  
  // ====== System Enum Types ======
  /** Enum Equal Id = 475 */
  type EnumGeneric = "TODO";
  /** Enum Equal Id = 476 */
  type EnumComparisonOperators = "TODO";
  /** Enum Equal Id = 477 */
  type EnumLogicalOperators = "TODO";
  /** Enum Equal Id = 478 */
  type EnumMathematicalOperators = "TODO";
  /** Enum Equal Id = 479 */
  type EnumAttackShapes = "TODO";
  /** Enum Equal Id = 480 */
  type EnumSurvivalStatus = "TODO";
  /** Enum Equal Id = 481 */
  type EnumSortingRules = "TODO";
  /** Enum Equal Id = 482 */
  type EnumRoundingLogic =
    | "Round"
    | "RoundUp"
    | "RoundDown"
    | "Truncate"
    ;
  /** Enum Equal Id = 483 */
  type EnumTypeConversions = "TODO";
  /** Enum Equal Id = 484 */
  type EnumMotionPathPointTypes = "TODO";
  /** Enum Equal Id = 485 */
  type EnumMotionTypes = "TODO";
  /** Enum Equal Id = 486 */
  type EnumFollowLocationType = "TODO";
  /** Enum Equal Id = 487 */
  type EnumCoordinateSystemType = "TODO";
  /** Enum Equal Id = 488 */
  type EnumElementalType = "TODO";
  /** Enum Equal Id = 489 */
  type EnumEntityType =
    | "Stage"
    | "Object"
    | "Player"
    | "Character"
    | "Creation"
    ;
  /** Enum Equal Id = 491 */
  type EnumUnitStatusAdditionResult = "TODO";
  /** Enum Equal Id = 492 */
  type EnumUnitStatusRemovalReason = "TODO";
  /** Enum Equal Id = 493 */
  type EnumUnitStatusRemovalStrategy = "TODO";
  /** Enum Equal Id = 494 */
  type EnumRevivePointSelectionStrategy = "TODO";
  /** Enum Equal Id = 495 */
  type EnumCauseOfBeingDown =
    | "NodeGraph"
    | "Defeat"
    | "Accident"
    ;
  /** Enum Equal Id = 496 */
  type EnumTrigonometricFunctions = "TODO";
  /** Enum Equal Id = 497 */
  type EnumDisruptorDeviceTypes = "TODO";
  /** Enum Equal Id = 498 */
  type EnumDisruptorDeviceOrientation = "TODO";
  /** Enum Equal Id = 499 */
  type EnumUIControlGroupStatus = "TODO";
  /** Enum Equal Id = 500 */
  type EnumTargetType = "TODO";
  /** Enum Equal Id = 501 */
  type EnumTriggerRestriction = "TODO";
  /** Enum Equal Id = 502 */
  type EnumHitType = "TODO";
  /** Enum Equal Id = 503 */
  type EnumAttackType = "TODO";
  /** Enum Equal Id = 504 */
  type EnumHitPerformanceLevel = "TODO";
  /** Enum Equal Id = 3351 */
  type EnumSkillSlot =
    | "Attack"
    | "E"
    | "Q"
    | "R"
    | "T"
    | "Custom"
    ;
  /** Enum Equal Id = 3352 */
  type EnumSoundAttenuationMode = "TODO";
  /** Enum Equal Id = 3353 */
  type EnumSelectCompletionReason = "TODO";
  /** Enum Equal Id = 3354 */
  type EnumSettlementStatus = "TODO";
  /** Enum Equal Id = 3356 */
  type EnumReasonForItemChange = "TODO";
  /** Enum Equal Id = 3357 */
  type EnumItemLootType = "TODO";
  /** Enum Equal Id = 3358 */
  type EnumDecisionRefreshMode = "TODO";
  /** Enum Equal Id = 3359 */
  type EnumElementalReactionType = "TODO";
  /** Enum Equal Id = 759 */
  type EnumInterruptStatus = "TODO";
  /** Enum Equal Id = 776 */
  type EnumGameplayMode =
    | "PlayTest"
    | "RoomPlay"
    | "MatchmakingPlay"
    ;
  /** Enum Equal Id = 777 */
  type EnumInputDeviceType =
    | "Keyboard"
    | "Gamepad"
    | "Touchscreen"
    ;
  
  // ====== System Extended Types ======
  type Count = number;
  type CountDown = number;
  class EntityVarSnapshot {
    type: "EntityVarSnapshot";
  }

  
  // ====== Math Namespace ======
  namespace m {
    // function equal(x: int, y: int): boolean;
    function equal(x: Str, y: Str): boolean;
    function equal(x: str, y: str): boolean;
    function equal(x: GUID, y: GUID): boolean;
    function equal(x: Entity, y: Entity): boolean;
    function equal(x: Vec, y: Vec): boolean;
    function equal(x: Faction, y: Faction): boolean;
    function equal(x: Int, y: Int): boolean;
    function equal(x: int, y: int): boolean;
    function equal(x: Float, y: Float): boolean;
    function equal(x: ConfigId, y: ConfigId): boolean;
    function equal(x: Prefab, y: Prefab): boolean;
    function equal(e1: EnumGeneric, e2: EnumGeneric): boolean;
    function equal(e1: EnumComparisonOperators, e2: EnumComparisonOperators): boolean;
    function equal(e1: EnumLogicalOperators, e2: EnumLogicalOperators): boolean;
    function equal(e1: EnumMathematicalOperators, e2: EnumMathematicalOperators): boolean;
    function equal(e1: EnumAttackShapes, e2: EnumAttackShapes): boolean;
    function equal(e1: EnumSurvivalStatus, e2: EnumSurvivalStatus): boolean;
    function equal(e1: EnumSortingRules, e2: EnumSortingRules): boolean;
    function equal(e1: EnumRoundingLogic, e2: EnumRoundingLogic): boolean;
    function equal(e1: EnumTypeConversions, e2: EnumTypeConversions): boolean;
    function equal(e1: EnumMotionPathPointTypes, e2: EnumMotionPathPointTypes): boolean;
    function equal(e1: EnumMotionTypes, e2: EnumMotionTypes): boolean;
    function equal(e1: EnumFollowLocationType, e2: EnumFollowLocationType): boolean;
    function equal(e1: EnumCoordinateSystemType, e2: EnumCoordinateSystemType): boolean;
    function equal(e1: EnumElementalType, e2: EnumElementalType): boolean;
    function equal(e1: EnumEntityType, e2: EnumEntityType): boolean;
    function equal(e1: EnumUnitStatusAdditionResult, e2: EnumUnitStatusAdditionResult): boolean;
    function equal(e1: EnumUnitStatusRemovalReason, e2: EnumUnitStatusRemovalReason): boolean;
    function equal(e1: EnumUnitStatusRemovalStrategy, e2: EnumUnitStatusRemovalStrategy): boolean;
    function equal(e1: EnumRevivePointSelectionStrategy, e2: EnumRevivePointSelectionStrategy): boolean;
    function equal(e1: EnumCauseOfBeingDown, e2: EnumCauseOfBeingDown): boolean;
    function equal(e1: EnumTrigonometricFunctions, e2: EnumTrigonometricFunctions): boolean;
    function equal(e1: EnumDisruptorDeviceTypes, e2: EnumDisruptorDeviceTypes): boolean;
    function equal(e1: EnumDisruptorDeviceOrientation, e2: EnumDisruptorDeviceOrientation): boolean;
    function equal(e1: EnumUIControlGroupStatus, e2: EnumUIControlGroupStatus): boolean;
    function equal(e1: EnumTargetType, e2: EnumTargetType): boolean;
    function equal(e1: EnumTriggerRestriction, e2: EnumTriggerRestriction): boolean;
    function equal(e1: EnumHitType, e2: EnumHitType): boolean;
    function equal(e1: EnumAttackType, e2: EnumAttackType): boolean;
    function equal(e1: EnumHitPerformanceLevel, e2: EnumHitPerformanceLevel): boolean;
    function equal(e1: EnumSkillSlot, e2: EnumSkillSlot): boolean;
    function equal(e1: EnumSoundAttenuationMode, e2: EnumSoundAttenuationMode): boolean;
    function equal(e1: EnumSelectCompletionReason, e2: EnumSelectCompletionReason): boolean;
    function equal(e1: EnumSettlementStatus, e2: EnumSettlementStatus): boolean;
    function equal(e1: EnumReasonForItemChange, e2: EnumReasonForItemChange): boolean;
    function equal(e1: EnumItemLootType, e2: EnumItemLootType): boolean;
    function equal(e1: EnumDecisionRefreshMode, e2: EnumDecisionRefreshMode): boolean;
    function equal(e1: EnumElementalReactionType, e2: EnumElementalReactionType): boolean;
    function equal(e1: EnumInterruptStatus, e2: EnumInterruptStatus): boolean;
    function equal(e1: EnumGameplayMode, e2: EnumGameplayMode): boolean;
    function equal(e1: EnumInputDeviceType, e2: EnumInputDeviceType): boolean;
    
    // ====== Type Convert ======
    function int(x: bool | float | Bool | Float): int;
    function Int(x: bool | float | Bool | Float): Int;
    function bool(x: int | Int): bool;
    function Bool(x: int | Int): Bool;
    function float(x: int | Int): float;
    function Float(x: int | Int): Float;
    function str(x: int | bool | float | Int | Bool | Float): str;
    function Str(x: int | bool | float | Int | Bool | Float): Str;
    function str(x: Vec | GUID | Entity | Faction): str;
    function Str(x: Vec | GUID | Entity | Faction): Str;
    
    function vec(x: int, y: int, z: int): Vec;
    function vec([x, y, z]: [int, int, int]): Vec;
    function split_vec(v: Vec): [x: int, y: int, z: int];
    
    // ====== List ====== //
    /** @deprecated Please use list.length directly. */
    function list_len(list: List): int;
    function maximum(int_list: List): int;
    function maximum(float_list: List): float;
    function minimum(int_list: List): int;
    function minimum(float_list: List): float;
    
    // function list(...items: ANY[]): List;
    // function list(items: ANY[]): List;
    // /** @deprecated Please use `list.find(item)` directly. */
    // function indices_of(list: List, item: ANY): int;
    // /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    // function list_item(list: List, index: int): ANY;
    // /** @deprecated Please use `list.includes(item)` directly. */
    // function includes(list: List, item: ANY): boolean;
    function list(...items: Entity[]): List;
    function list(items: Entity[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Entity): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Entity;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Entity): boolean;
    
    function list(...items: GUID[]): List;
    function list(items: GUID[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: GUID): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): GUID;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: GUID): boolean;
    
    function list(...items: Int[]): List;
    function list(items: Int[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Int): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Int;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Int): boolean;
    
    function list(...items: Bool[]): List;
    function list(items: Bool[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Bool): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Bool;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Bool): boolean;
    
    function list(...items: Float[]): List;
    function list(items: Float[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Float): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Float;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Float): boolean;
    
    function list(...items: Str[]): List;
    function list(items: Str[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Str): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Str;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Str): boolean;
    
    function list(...items: int[]): List;
    function list(items: int[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: int): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): int;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: int): boolean;
    
    function list(...items: bool[]): List;
    function list(items: bool[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: bool): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): bool;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: bool): boolean;
    
    function list(...items: float[]): List;
    function list(items: float[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: float): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): float;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: float): boolean;
    
    function list(...items: str[]): List;
    function list(items: str[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: str): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): str;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: str): boolean;
    
    function list(...items: Faction[]): List;
    function list(items: Faction[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Faction): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Faction;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Faction): boolean;
    
    function list(...items: Vec[]): List;
    function list(items: Vec[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Vec): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Vec;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Vec): boolean;
    
    function list(...items: ConfigId[]): List;
    function list(items: ConfigId[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: ConfigId): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): ConfigId;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: ConfigId): boolean;
    
    function list(...items: Prefab[]): List;
    function list(items: Prefab[]): List;
    /** @deprecated Please use `list.find(item)` directly. */
    function indices_of(list: List, item: Prefab): int;
    /** @deprecated Please use `list[index]` or `list.get(index)` directly. */
    function list_item(list: List, index: int): Prefab;
    /** @deprecated Please use `list.includes(item)` directly. */
    function includes(list: List, item: Prefab): boolean;
    
    
    
    // ====== Dict ====== //
    /** @deprecated Please use `dict.keys()` directly. */
    function dict_keys(): List;
    /** @deprecated Please use `dict.vals()` directly. */
    function dict_values(): List;
    
    function dict(keys: List, values: List): Dict;
    // function dict(pairs: [KEY, VALUE][]): Dict;
    // function dict(...pairs: [KEY, VALUE][]): Dict;
    // function dict(...pairs: (KEY | VALUE)[]): Dict;
    // /** @deprecated Please use `dict.has(key)` directly. */
    // function dict_has_key(dict: Dict, key: KEY): boolean;
    // /** @deprecated Please use `dict.get(key)` directly. */
    // function dict_get(): KEY;
    // /** @deprecated Please use `dict.includes(val)` directly. */
    // function dict_has_val(dict: Dict, value: VALUE): boolean;
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: Entity): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): Entity;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: GUID): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): GUID;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: Int): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): Int;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: Str): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): Str;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: int): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): int;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: str): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): str;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: Faction): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): Faction;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: ConfigId): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): ConfigId;
    
    /** @deprecated Please use `dict.has(key)` directly. */
    function dict_has_key(dict: Dict, key: Prefab): boolean;
    /** @deprecated Please use `dict.get(key)` directly. */
    function dict_get(): Prefab;
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Entity): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: GUID): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Int): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Bool): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Float): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Str): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: int): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: bool): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: float): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: str): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Faction): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Vec): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: ConfigId): boolean;
    
    /** @deprecated Please use `dict.includes(val)` directly. */
    function dict_has_val(dict: Dict, value: Prefab): boolean;
    function dict(pairs: [Entity, Entity][]): Dict;
    function dict(...pairs: [Entity, Entity][]): Dict;
    function dict(...pairs: (Entity | Entity)[]): Dict;
    
    function dict(pairs: [Entity, GUID][]): Dict;
    function dict(...pairs: [Entity, GUID][]): Dict;
    function dict(...pairs: (Entity | GUID)[]): Dict;
    
    function dict(pairs: [Entity, Int][]): Dict;
    function dict(...pairs: [Entity, Int][]): Dict;
    function dict(...pairs: (Entity | Int)[]): Dict;
    
    function dict(pairs: [Entity, Bool][]): Dict;
    function dict(...pairs: [Entity, Bool][]): Dict;
    function dict(...pairs: (Entity | Bool)[]): Dict;
    
    function dict(pairs: [Entity, Float][]): Dict;
    function dict(...pairs: [Entity, Float][]): Dict;
    function dict(...pairs: (Entity | Float)[]): Dict;
    
    function dict(pairs: [Entity, Str][]): Dict;
    function dict(...pairs: [Entity, Str][]): Dict;
    function dict(...pairs: (Entity | Str)[]): Dict;
    
    function dict(pairs: [Entity, int][]): Dict;
    function dict(...pairs: [Entity, int][]): Dict;
    function dict(...pairs: (Entity | int)[]): Dict;
    
    function dict(pairs: [Entity, bool][]): Dict;
    function dict(...pairs: [Entity, bool][]): Dict;
    function dict(...pairs: (Entity | bool)[]): Dict;
    
    function dict(pairs: [Entity, float][]): Dict;
    function dict(...pairs: [Entity, float][]): Dict;
    function dict(...pairs: (Entity | float)[]): Dict;
    
    function dict(pairs: [Entity, str][]): Dict;
    function dict(...pairs: [Entity, str][]): Dict;
    function dict(...pairs: (Entity | str)[]): Dict;
    
    function dict(pairs: [Entity, Faction][]): Dict;
    function dict(...pairs: [Entity, Faction][]): Dict;
    function dict(...pairs: (Entity | Faction)[]): Dict;
    
    function dict(pairs: [Entity, Vec][]): Dict;
    function dict(...pairs: [Entity, Vec][]): Dict;
    function dict(...pairs: (Entity | Vec)[]): Dict;
    
    function dict(pairs: [Entity, ConfigId][]): Dict;
    function dict(...pairs: [Entity, ConfigId][]): Dict;
    function dict(...pairs: (Entity | ConfigId)[]): Dict;
    
    function dict(pairs: [Entity, Prefab][]): Dict;
    function dict(...pairs: [Entity, Prefab][]): Dict;
    function dict(...pairs: (Entity | Prefab)[]): Dict;
    
    function dict(pairs: [GUID, Entity][]): Dict;
    function dict(...pairs: [GUID, Entity][]): Dict;
    function dict(...pairs: (GUID | Entity)[]): Dict;
    
    function dict(pairs: [GUID, GUID][]): Dict;
    function dict(...pairs: [GUID, GUID][]): Dict;
    function dict(...pairs: (GUID | GUID)[]): Dict;
    
    function dict(pairs: [GUID, Int][]): Dict;
    function dict(...pairs: [GUID, Int][]): Dict;
    function dict(...pairs: (GUID | Int)[]): Dict;
    
    function dict(pairs: [GUID, Bool][]): Dict;
    function dict(...pairs: [GUID, Bool][]): Dict;
    function dict(...pairs: (GUID | Bool)[]): Dict;
    
    function dict(pairs: [GUID, Float][]): Dict;
    function dict(...pairs: [GUID, Float][]): Dict;
    function dict(...pairs: (GUID | Float)[]): Dict;
    
    function dict(pairs: [GUID, Str][]): Dict;
    function dict(...pairs: [GUID, Str][]): Dict;
    function dict(...pairs: (GUID | Str)[]): Dict;
    
    function dict(pairs: [GUID, int][]): Dict;
    function dict(...pairs: [GUID, int][]): Dict;
    function dict(...pairs: (GUID | int)[]): Dict;
    
    function dict(pairs: [GUID, bool][]): Dict;
    function dict(...pairs: [GUID, bool][]): Dict;
    function dict(...pairs: (GUID | bool)[]): Dict;
    
    function dict(pairs: [GUID, float][]): Dict;
    function dict(...pairs: [GUID, float][]): Dict;
    function dict(...pairs: (GUID | float)[]): Dict;
    
    function dict(pairs: [GUID, str][]): Dict;
    function dict(...pairs: [GUID, str][]): Dict;
    function dict(...pairs: (GUID | str)[]): Dict;
    
    function dict(pairs: [GUID, Faction][]): Dict;
    function dict(...pairs: [GUID, Faction][]): Dict;
    function dict(...pairs: (GUID | Faction)[]): Dict;
    
    function dict(pairs: [GUID, Vec][]): Dict;
    function dict(...pairs: [GUID, Vec][]): Dict;
    function dict(...pairs: (GUID | Vec)[]): Dict;
    
    function dict(pairs: [GUID, ConfigId][]): Dict;
    function dict(...pairs: [GUID, ConfigId][]): Dict;
    function dict(...pairs: (GUID | ConfigId)[]): Dict;
    
    function dict(pairs: [GUID, Prefab][]): Dict;
    function dict(...pairs: [GUID, Prefab][]): Dict;
    function dict(...pairs: (GUID | Prefab)[]): Dict;
    
    function dict(pairs: [Int, Entity][]): Dict;
    function dict(...pairs: [Int, Entity][]): Dict;
    function dict(...pairs: (Int | Entity)[]): Dict;
    
    function dict(pairs: [Int, GUID][]): Dict;
    function dict(...pairs: [Int, GUID][]): Dict;
    function dict(...pairs: (Int | GUID)[]): Dict;
    
    function dict(pairs: [Int, Int][]): Dict;
    function dict(...pairs: [Int, Int][]): Dict;
    function dict(...pairs: (Int | Int)[]): Dict;
    
    function dict(pairs: [Int, Bool][]): Dict;
    function dict(...pairs: [Int, Bool][]): Dict;
    function dict(...pairs: (Int | Bool)[]): Dict;
    
    function dict(pairs: [Int, Float][]): Dict;
    function dict(...pairs: [Int, Float][]): Dict;
    function dict(...pairs: (Int | Float)[]): Dict;
    
    function dict(pairs: [Int, Str][]): Dict;
    function dict(...pairs: [Int, Str][]): Dict;
    function dict(...pairs: (Int | Str)[]): Dict;
    
    function dict(pairs: [Int, int][]): Dict;
    function dict(...pairs: [Int, int][]): Dict;
    function dict(...pairs: (Int | int)[]): Dict;
    
    function dict(pairs: [Int, bool][]): Dict;
    function dict(...pairs: [Int, bool][]): Dict;
    function dict(...pairs: (Int | bool)[]): Dict;
    
    function dict(pairs: [Int, float][]): Dict;
    function dict(...pairs: [Int, float][]): Dict;
    function dict(...pairs: (Int | float)[]): Dict;
    
    function dict(pairs: [Int, str][]): Dict;
    function dict(...pairs: [Int, str][]): Dict;
    function dict(...pairs: (Int | str)[]): Dict;
    
    function dict(pairs: [Int, Faction][]): Dict;
    function dict(...pairs: [Int, Faction][]): Dict;
    function dict(...pairs: (Int | Faction)[]): Dict;
    
    function dict(pairs: [Int, Vec][]): Dict;
    function dict(...pairs: [Int, Vec][]): Dict;
    function dict(...pairs: (Int | Vec)[]): Dict;
    
    function dict(pairs: [Int, ConfigId][]): Dict;
    function dict(...pairs: [Int, ConfigId][]): Dict;
    function dict(...pairs: (Int | ConfigId)[]): Dict;
    
    function dict(pairs: [Int, Prefab][]): Dict;
    function dict(...pairs: [Int, Prefab][]): Dict;
    function dict(...pairs: (Int | Prefab)[]): Dict;
    
    function dict(pairs: [Str, Entity][]): Dict;
    function dict(...pairs: [Str, Entity][]): Dict;
    function dict(...pairs: (Str | Entity)[]): Dict;
    
    function dict(pairs: [Str, GUID][]): Dict;
    function dict(...pairs: [Str, GUID][]): Dict;
    function dict(...pairs: (Str | GUID)[]): Dict;
    
    function dict(pairs: [Str, Int][]): Dict;
    function dict(...pairs: [Str, Int][]): Dict;
    function dict(...pairs: (Str | Int)[]): Dict;
    
    function dict(pairs: [Str, Bool][]): Dict;
    function dict(...pairs: [Str, Bool][]): Dict;
    function dict(...pairs: (Str | Bool)[]): Dict;
    
    function dict(pairs: [Str, Float][]): Dict;
    function dict(...pairs: [Str, Float][]): Dict;
    function dict(...pairs: (Str | Float)[]): Dict;
    
    function dict(pairs: [Str, Str][]): Dict;
    function dict(...pairs: [Str, Str][]): Dict;
    function dict(...pairs: (Str | Str)[]): Dict;
    
    function dict(pairs: [Str, int][]): Dict;
    function dict(...pairs: [Str, int][]): Dict;
    function dict(...pairs: (Str | int)[]): Dict;
    
    function dict(pairs: [Str, bool][]): Dict;
    function dict(...pairs: [Str, bool][]): Dict;
    function dict(...pairs: (Str | bool)[]): Dict;
    
    function dict(pairs: [Str, float][]): Dict;
    function dict(...pairs: [Str, float][]): Dict;
    function dict(...pairs: (Str | float)[]): Dict;
    
    function dict(pairs: [Str, str][]): Dict;
    function dict(...pairs: [Str, str][]): Dict;
    function dict(...pairs: (Str | str)[]): Dict;
    
    function dict(pairs: [Str, Faction][]): Dict;
    function dict(...pairs: [Str, Faction][]): Dict;
    function dict(...pairs: (Str | Faction)[]): Dict;
    
    function dict(pairs: [Str, Vec][]): Dict;
    function dict(...pairs: [Str, Vec][]): Dict;
    function dict(...pairs: (Str | Vec)[]): Dict;
    
    function dict(pairs: [Str, ConfigId][]): Dict;
    function dict(...pairs: [Str, ConfigId][]): Dict;
    function dict(...pairs: (Str | ConfigId)[]): Dict;
    
    function dict(pairs: [Str, Prefab][]): Dict;
    function dict(...pairs: [Str, Prefab][]): Dict;
    function dict(...pairs: (Str | Prefab)[]): Dict;
    
    function dict(pairs: [int, Entity][]): Dict;
    function dict(...pairs: [int, Entity][]): Dict;
    function dict(...pairs: (int | Entity)[]): Dict;
    
    function dict(pairs: [int, GUID][]): Dict;
    function dict(...pairs: [int, GUID][]): Dict;
    function dict(...pairs: (int | GUID)[]): Dict;
    
    function dict(pairs: [int, Int][]): Dict;
    function dict(...pairs: [int, Int][]): Dict;
    function dict(...pairs: (int | Int)[]): Dict;
    
    function dict(pairs: [int, Bool][]): Dict;
    function dict(...pairs: [int, Bool][]): Dict;
    function dict(...pairs: (int | Bool)[]): Dict;
    
    function dict(pairs: [int, Float][]): Dict;
    function dict(...pairs: [int, Float][]): Dict;
    function dict(...pairs: (int | Float)[]): Dict;
    
    function dict(pairs: [int, Str][]): Dict;
    function dict(...pairs: [int, Str][]): Dict;
    function dict(...pairs: (int | Str)[]): Dict;
    
    function dict(pairs: [int, int][]): Dict;
    function dict(...pairs: [int, int][]): Dict;
    function dict(...pairs: (int | int)[]): Dict;
    
    function dict(pairs: [int, bool][]): Dict;
    function dict(...pairs: [int, bool][]): Dict;
    function dict(...pairs: (int | bool)[]): Dict;
    
    function dict(pairs: [int, float][]): Dict;
    function dict(...pairs: [int, float][]): Dict;
    function dict(...pairs: (int | float)[]): Dict;
    
    function dict(pairs: [int, str][]): Dict;
    function dict(...pairs: [int, str][]): Dict;
    function dict(...pairs: (int | str)[]): Dict;
    
    function dict(pairs: [int, Faction][]): Dict;
    function dict(...pairs: [int, Faction][]): Dict;
    function dict(...pairs: (int | Faction)[]): Dict;
    
    function dict(pairs: [int, Vec][]): Dict;
    function dict(...pairs: [int, Vec][]): Dict;
    function dict(...pairs: (int | Vec)[]): Dict;
    
    function dict(pairs: [int, ConfigId][]): Dict;
    function dict(...pairs: [int, ConfigId][]): Dict;
    function dict(...pairs: (int | ConfigId)[]): Dict;
    
    function dict(pairs: [int, Prefab][]): Dict;
    function dict(...pairs: [int, Prefab][]): Dict;
    function dict(...pairs: (int | Prefab)[]): Dict;
    
    function dict(pairs: [str, Entity][]): Dict;
    function dict(...pairs: [str, Entity][]): Dict;
    function dict(...pairs: (str | Entity)[]): Dict;
    
    function dict(pairs: [str, GUID][]): Dict;
    function dict(...pairs: [str, GUID][]): Dict;
    function dict(...pairs: (str | GUID)[]): Dict;
    
    function dict(pairs: [str, Int][]): Dict;
    function dict(...pairs: [str, Int][]): Dict;
    function dict(...pairs: (str | Int)[]): Dict;
    
    function dict(pairs: [str, Bool][]): Dict;
    function dict(...pairs: [str, Bool][]): Dict;
    function dict(...pairs: (str | Bool)[]): Dict;
    
    function dict(pairs: [str, Float][]): Dict;
    function dict(...pairs: [str, Float][]): Dict;
    function dict(...pairs: (str | Float)[]): Dict;
    
    function dict(pairs: [str, Str][]): Dict;
    function dict(...pairs: [str, Str][]): Dict;
    function dict(...pairs: (str | Str)[]): Dict;
    
    function dict(pairs: [str, int][]): Dict;
    function dict(...pairs: [str, int][]): Dict;
    function dict(...pairs: (str | int)[]): Dict;
    
    function dict(pairs: [str, bool][]): Dict;
    function dict(...pairs: [str, bool][]): Dict;
    function dict(...pairs: (str | bool)[]): Dict;
    
    function dict(pairs: [str, float][]): Dict;
    function dict(...pairs: [str, float][]): Dict;
    function dict(...pairs: (str | float)[]): Dict;
    
    function dict(pairs: [str, str][]): Dict;
    function dict(...pairs: [str, str][]): Dict;
    function dict(...pairs: (str | str)[]): Dict;
    
    function dict(pairs: [str, Faction][]): Dict;
    function dict(...pairs: [str, Faction][]): Dict;
    function dict(...pairs: (str | Faction)[]): Dict;
    
    function dict(pairs: [str, Vec][]): Dict;
    function dict(...pairs: [str, Vec][]): Dict;
    function dict(...pairs: (str | Vec)[]): Dict;
    
    function dict(pairs: [str, ConfigId][]): Dict;
    function dict(...pairs: [str, ConfigId][]): Dict;
    function dict(...pairs: (str | ConfigId)[]): Dict;
    
    function dict(pairs: [str, Prefab][]): Dict;
    function dict(...pairs: [str, Prefab][]): Dict;
    function dict(...pairs: (str | Prefab)[]): Dict;
    
    function dict(pairs: [Faction, Entity][]): Dict;
    function dict(...pairs: [Faction, Entity][]): Dict;
    function dict(...pairs: (Faction | Entity)[]): Dict;
    
    function dict(pairs: [Faction, GUID][]): Dict;
    function dict(...pairs: [Faction, GUID][]): Dict;
    function dict(...pairs: (Faction | GUID)[]): Dict;
    
    function dict(pairs: [Faction, Int][]): Dict;
    function dict(...pairs: [Faction, Int][]): Dict;
    function dict(...pairs: (Faction | Int)[]): Dict;
    
    function dict(pairs: [Faction, Bool][]): Dict;
    function dict(...pairs: [Faction, Bool][]): Dict;
    function dict(...pairs: (Faction | Bool)[]): Dict;
    
    function dict(pairs: [Faction, Float][]): Dict;
    function dict(...pairs: [Faction, Float][]): Dict;
    function dict(...pairs: (Faction | Float)[]): Dict;
    
    function dict(pairs: [Faction, Str][]): Dict;
    function dict(...pairs: [Faction, Str][]): Dict;
    function dict(...pairs: (Faction | Str)[]): Dict;
    
    function dict(pairs: [Faction, int][]): Dict;
    function dict(...pairs: [Faction, int][]): Dict;
    function dict(...pairs: (Faction | int)[]): Dict;
    
    function dict(pairs: [Faction, bool][]): Dict;
    function dict(...pairs: [Faction, bool][]): Dict;
    function dict(...pairs: (Faction | bool)[]): Dict;
    
    function dict(pairs: [Faction, float][]): Dict;
    function dict(...pairs: [Faction, float][]): Dict;
    function dict(...pairs: (Faction | float)[]): Dict;
    
    function dict(pairs: [Faction, str][]): Dict;
    function dict(...pairs: [Faction, str][]): Dict;
    function dict(...pairs: (Faction | str)[]): Dict;
    
    function dict(pairs: [Faction, Faction][]): Dict;
    function dict(...pairs: [Faction, Faction][]): Dict;
    function dict(...pairs: (Faction | Faction)[]): Dict;
    
    function dict(pairs: [Faction, Vec][]): Dict;
    function dict(...pairs: [Faction, Vec][]): Dict;
    function dict(...pairs: (Faction | Vec)[]): Dict;
    
    function dict(pairs: [Faction, ConfigId][]): Dict;
    function dict(...pairs: [Faction, ConfigId][]): Dict;
    function dict(...pairs: (Faction | ConfigId)[]): Dict;
    
    function dict(pairs: [Faction, Prefab][]): Dict;
    function dict(...pairs: [Faction, Prefab][]): Dict;
    function dict(...pairs: (Faction | Prefab)[]): Dict;
    
    function dict(pairs: [ConfigId, Entity][]): Dict;
    function dict(...pairs: [ConfigId, Entity][]): Dict;
    function dict(...pairs: (ConfigId | Entity)[]): Dict;
    
    function dict(pairs: [ConfigId, GUID][]): Dict;
    function dict(...pairs: [ConfigId, GUID][]): Dict;
    function dict(...pairs: (ConfigId | GUID)[]): Dict;
    
    function dict(pairs: [ConfigId, Int][]): Dict;
    function dict(...pairs: [ConfigId, Int][]): Dict;
    function dict(...pairs: (ConfigId | Int)[]): Dict;
    
    function dict(pairs: [ConfigId, Bool][]): Dict;
    function dict(...pairs: [ConfigId, Bool][]): Dict;
    function dict(...pairs: (ConfigId | Bool)[]): Dict;
    
    function dict(pairs: [ConfigId, Float][]): Dict;
    function dict(...pairs: [ConfigId, Float][]): Dict;
    function dict(...pairs: (ConfigId | Float)[]): Dict;
    
    function dict(pairs: [ConfigId, Str][]): Dict;
    function dict(...pairs: [ConfigId, Str][]): Dict;
    function dict(...pairs: (ConfigId | Str)[]): Dict;
    
    function dict(pairs: [ConfigId, int][]): Dict;
    function dict(...pairs: [ConfigId, int][]): Dict;
    function dict(...pairs: (ConfigId | int)[]): Dict;
    
    function dict(pairs: [ConfigId, bool][]): Dict;
    function dict(...pairs: [ConfigId, bool][]): Dict;
    function dict(...pairs: (ConfigId | bool)[]): Dict;
    
    function dict(pairs: [ConfigId, float][]): Dict;
    function dict(...pairs: [ConfigId, float][]): Dict;
    function dict(...pairs: (ConfigId | float)[]): Dict;
    
    function dict(pairs: [ConfigId, str][]): Dict;
    function dict(...pairs: [ConfigId, str][]): Dict;
    function dict(...pairs: (ConfigId | str)[]): Dict;
    
    function dict(pairs: [ConfigId, Faction][]): Dict;
    function dict(...pairs: [ConfigId, Faction][]): Dict;
    function dict(...pairs: (ConfigId | Faction)[]): Dict;
    
    function dict(pairs: [ConfigId, Vec][]): Dict;
    function dict(...pairs: [ConfigId, Vec][]): Dict;
    function dict(...pairs: (ConfigId | Vec)[]): Dict;
    
    function dict(pairs: [ConfigId, ConfigId][]): Dict;
    function dict(...pairs: [ConfigId, ConfigId][]): Dict;
    function dict(...pairs: (ConfigId | ConfigId)[]): Dict;
    
    function dict(pairs: [ConfigId, Prefab][]): Dict;
    function dict(...pairs: [ConfigId, Prefab][]): Dict;
    function dict(...pairs: (ConfigId | Prefab)[]): Dict;
    
    function dict(pairs: [Prefab, Entity][]): Dict;
    function dict(...pairs: [Prefab, Entity][]): Dict;
    function dict(...pairs: (Prefab | Entity)[]): Dict;
    
    function dict(pairs: [Prefab, GUID][]): Dict;
    function dict(...pairs: [Prefab, GUID][]): Dict;
    function dict(...pairs: (Prefab | GUID)[]): Dict;
    
    function dict(pairs: [Prefab, Int][]): Dict;
    function dict(...pairs: [Prefab, Int][]): Dict;
    function dict(...pairs: (Prefab | Int)[]): Dict;
    
    function dict(pairs: [Prefab, Bool][]): Dict;
    function dict(...pairs: [Prefab, Bool][]): Dict;
    function dict(...pairs: (Prefab | Bool)[]): Dict;
    
    function dict(pairs: [Prefab, Float][]): Dict;
    function dict(...pairs: [Prefab, Float][]): Dict;
    function dict(...pairs: (Prefab | Float)[]): Dict;
    
    function dict(pairs: [Prefab, Str][]): Dict;
    function dict(...pairs: [Prefab, Str][]): Dict;
    function dict(...pairs: (Prefab | Str)[]): Dict;
    
    function dict(pairs: [Prefab, int][]): Dict;
    function dict(...pairs: [Prefab, int][]): Dict;
    function dict(...pairs: (Prefab | int)[]): Dict;
    
    function dict(pairs: [Prefab, bool][]): Dict;
    function dict(...pairs: [Prefab, bool][]): Dict;
    function dict(...pairs: (Prefab | bool)[]): Dict;
    
    function dict(pairs: [Prefab, float][]): Dict;
    function dict(...pairs: [Prefab, float][]): Dict;
    function dict(...pairs: (Prefab | float)[]): Dict;
    
    function dict(pairs: [Prefab, str][]): Dict;
    function dict(...pairs: [Prefab, str][]): Dict;
    function dict(...pairs: (Prefab | str)[]): Dict;
    
    function dict(pairs: [Prefab, Faction][]): Dict;
    function dict(...pairs: [Prefab, Faction][]): Dict;
    function dict(...pairs: (Prefab | Faction)[]): Dict;
    
    function dict(pairs: [Prefab, Vec][]): Dict;
    function dict(...pairs: [Prefab, Vec][]): Dict;
    function dict(...pairs: (Prefab | Vec)[]): Dict;
    
    function dict(pairs: [Prefab, ConfigId][]): Dict;
    function dict(...pairs: [Prefab, ConfigId][]): Dict;
    function dict(...pairs: (Prefab | ConfigId)[]): Dict;
    
    function dict(pairs: [Prefab, Prefab][]): Dict;
    function dict(...pairs: [Prefab, Prefab][]): Dict;
    function dict(...pairs: (Prefab | Prefab)[]): Dict;
    
    
    function struct(name: string, ...val: SysAllTypes[]): Struct;
    function struct(name: string, val: SysAllTypes[]): Struct;
    function struct(name: string, val: { [field: string]: SysAllTypes }): Struct;
    function split_struct(x: Struct): { [field: string]: SysAllTypes };
    
    
    function add(x: int | Int, y: int | Int): int;
    function Add(x: int | Int, y: int | Int): Int;
    function sub(x: int | Int, y: int | Int): int;
    function Sub(x: int | Int, y: int | Int): Int;
    function mul(x: int | Int, y: int | Int): int;
    function Mul(x: int | Int, y: int | Int): Int;
    function div(x: int | Int, y: int | Int): int;
    function Div(x: int | Int, y: int | Int): Int;
    function mod(x: int | Int, y: int | Int): int;
    function Mod(x: int | Int, y: int | Int): Int;
    function min(x: int | Int, y: int | Int): int;
    function Min(x: int | Int, y: int | Int): Int;
    function max(x: int | Int, y: int | Int): int;
    function Max(x: int | Int, y: int | Int): Int;
    function range(min: int | Int, max: int | Int, x: int | Int): int;
    function Range(min: int | Int, max: int | Int, x: int | Int): Int;
    function abs(x: int | Int): int;
    function abs(x: int | Int): Int;
    function sgn(x: int | Int): int;
    function Sgn(x: int | Int): Int;
    function shiftL(x: int | Int, offset: int | Int): int;
    function ShiftL(x: int | Int, offset: int | Int): Int;
    function shiftR(x: int | Int, offset: int | Int): int;
    function ShiftR(x: int | Int, offset: int | Int): Int;
    function bitand(x: int | Int, y: int | Int): int;
    function Bitand(x: int | Int, y: int | Int): Int;
    function bitor(x: int | Int, y: int | Int): int;
    function Bitor(x: int | Int, y: int | Int): Int;
    function bitxor(x: int | Int, y: int | Int): int;
    function Bitxor(x: int | Int, y: int | Int): Int;
    function bitnot(x: int | Int, y: int | Int): int;
    function Bitnot(x: int | Int, y: int | Int): Int;
    /** write x bitly from start to end(inclusive) */
    function bitwrite(target: int | Int, start: int | Int, end: int | Int, x: int | Int): int;
    function Bitwrite(target: int | Int, start: int | Int, end: int | Int, x: int | Int): Int;
    /** read x bitly from start to end(inclusive) */
    function bitread(src: int | Int, start: int | Int, end: int | Int): int;
    function Bitread(src: int | Int, start: int | Int, end: int | Int): Int;
    function add(x: float | Float, y: float | Float): float;
    function Add(x: float | Float, y: float | Float): Float;
    function sub(x: float | Float, y: float | Float): float;
    function Sub(x: float | Float, y: float | Float): Float;
    function mul(x: float | Float, y: float | Float): float;
    function Mul(x: float | Float, y: float | Float): Float;
    function div(x: float | Float, y: float | Float): float;
    function Div(x: float | Float, y: float | Float): Float;
    function min(x: float | Float, y: float | Float): float;
    function Min(x: float | Float, y: float | Float): Float;
    function max(x: float | Float, y: float | Float): float;
    function Max(x: float | Float, y: float | Float): Float;
    function range(x: float | Float, min: float | Float, max: float | Float): float;
    function Range(x: float | Float, min: float | Float, max: float | Float): Float;
    function log(x: float | Float, base: float | Float): float;
    function Log(x: float | Float, base: float | Float): Float;
    function pow(base: float | Float, x: float | Float): float;
    function Pow(base: float | Float, x: float | Float): Float;
    function cos(x: float | Float): float;
    function Cos(x: float | Float): Float;
    function sin(x: float | Float): float;
    function Sin(x: float | Float): Float;
    function tan(x: float | Float): float;
    function Tan(x: float | Float): Float;
    function acos(x: float | Float): float;
    function Acos(x: float | Float): Float;
    function asin(x: float | Float): float;
    function Asin(x: float | Float): Float;
    function atan(x: float | Float): float;
    function Atan(x: float | Float): Float;
    function deg(rad: float | Float): float;
    function Deg(rad: float | Float): Float;
    function rad(deg: float | Float): float;
    function Rad(deg: float | Float): Float;
    function abs(x: float | Float): float;
    function Abs(x: float | Float): Float;
    function sqrt(x: float | Float): float;
    function Sqrt(x: float | Float): Float;
    function sgn(x: float | Float): float;
    function Sgn(x: float | Float): Float;
    function round(x: float | Float, mode: EnumRoundMode): int;
    function Round(x: float | Float, mode: EnumRoundMode): Int;
    function floor(x: float | Float): int;
    function Floor(x: float | Float): Int;
    function ceil(x: float | Float): int;
    function Ceil(x: float | Float): Int;
    
    function gt(x: int | Int, y: int | Int): bool;
    function Gt(x: int | Int, y: int | Int): Bool;
    function ge(x: int | Int, y: int | Int): bool;
    function Ge(x: int | Int, y: int | Int): Bool;
    function lt(x: int | Int, y: int | Int): bool;
    function Lt(x: int | Int, y: int | Int): Bool;
    function le(x: int | Int, y: int | Int): bool;
    function Le(x: int | Int, y: int | Int): Bool;
    function gt(x: float | Float, y: float | Float): bool;
    function Gt(x: float | Float, y: float | Float): Bool;
    function ge(x: float | Float, y: float | Float): bool;
    function Ge(x: float | Float, y: float | Float): Bool;
    function lt(x: float | Float, y: float | Float): bool;
    function Lt(x: float | Float, y: float | Float): Bool;
    function le(x: float | Float, y: float | Float): bool;
    function Le(x: float | Float, y: float | Float): Bool;
    
    function not(x: bool | Bool): bool;
    function Not(x: bool | Bool): Bool;
    function or(x: bool | Bool): bool;
    function Or(x: bool | Bool): Bool;
    function xor(x: bool | Bool, y: bool | Bool): bool;
    function Xor(x: bool | Bool, y: bool | Bool): Bool;
    function and(x: bool | Bool, y: bool | Bool): bool;
    function And(x: bool | Bool, y: bool | Bool): Bool;
    // ---- Vec ---- //
    function distance(v1: Vec, v2: Vec): float;
    function Distance(v1: Vec, v2: Vec): Float;
    function normalize(v: Vec): Vec;
    /** Length of Vec */
    function norm(v: Vec): float;
    function Norm(v: Vec): Float;
    function add(v1: Vec, v2: Vec): Vec;
    function sub(v1: Vec, v2: Vec): Vec;
    function scale(v: Vec, x: float): Vec;
    function dot(v1: Vec, v2: Vec): float;
    function Dot(v1: Vec, v2: Vec): Float;
    function cross(v1: Vec, v2: Vec): Vec;
    /** rad */
    function angle(v1: Vec, v2: Vec): float;
    function Angle(v1: Vec, v2: Vec): Float;
    /** rot is in deg uint */
    function eula_rot(front: Vec, up: Vec): Vec;
    /** rot is in deg uint */
    function rotate(target: Vec, rot: Vec): Vec;
    
    // ---- Should in query but i put them here in math ---- //
    /** from min to max */
    function random(min: float | Float, max: float | Float): float;
    /** from min to max */
    function Random(min: float | Float, max: float | Float): Float;
    /** from 0 to max */
    function random(max: float | Float): float;
    /** from 0 to max */
    function Random(max: float | Float): Float;
    /** from 0 to 1 */
    function random(): float;
    /** from 0 to 1 */
    function Random(): Float;
    /** from min to max */
    function random(min: int | Int, max: int | Int): int;
    /** from min to max */
    function Random(min: int | Int, max: int | Int): Int;
    /** from 0 to max */
    function random(max: int | Int): int;
    /** from 0 to max */
    function Random(max: int | Int): Int;
    /** Random Weight using list of weights */
    function random(list: List): int;
    /** Random Weight using list of weights */
    function Random(list: List): Int;
    
    function ZERO(): Vec;
    function FRONT(): Vec;
    function BACK(): Vec;
    function UP(): Vec;
    function DOWN(): Vec;
    function LEFT(): Vec;
    function RIGHT(): Vec;
    
    function Pi(): float;
    function PI(): Float;
  }
  
  // ====== Query Namespace ======
  namespace q {
    function game_mode(): EnumGameMode;
    function player_num(): int;
    
    function timezone(): int;
    function timestamp(): int;
    
    function env_time(): float;
    function env_day(): int;
    function game_time(): int;
    
    function timer(name: string, src?: Entity): float;
    
    function device(player: Entity): EnumDevice;
    function which_ui(player: string): int;
    
    function target_of(creation: Entity): Entity;
    function aggro_of(creation: Entity): List;
    
    function snapshot(): { [key: string]: SysAllTypes };
    /** @deprecated Directly use `_local_var` */
    function local_var(): { [key: string]: SysAllTypes };
    /** @deprecated Directly use `Self.var` or `entity.var` */
    function custom_var(target: Entity): { [key: string]: SysAllTypes };
    /** @deprecated Directly use `Node.var` */
    function graph_var(): { [key: string]: SysAllTypes };
    /** @deprecated Directly use `Self` */
    function self(): { [key: string]: SysAllTypes };
    
    // ------ player ------ //
    function pre_status(index: int, target?: Entity): int;
    function speed(character?: Entity): float;
    function velocity(character?: Entity): Vec;
    
    function is_all_down(player: Entity): bool;
    function player(id: int): Entity;
    function player(character: Entity): Entity;
    function player_id(guid: GUID): int;
    
    function revive_time(player: Entity): int;
    function nickname(player: Entity): str;
    function left_revives(player: Entity): int;
    function all_players(): List;
    function all_characters(player: Entity): List;
    
    function level_of(player: Entity, class_id?: ConfigId): int;
    function class_id_of(player: Entity): ConfigId;
    function skill_of(player: Entity, skill_slot: EnumSkillSlot): ConfigId;
    // TODO: 16-22
    
    namespace attr {
      /** Character and Object and Creation */
      function level(target?: Entity): int;
      /** Character and Object and Creation */
      function hp(target?: Entity): float;
      /** Character and Object and Creation */
      function max_hp(target?: Entity): float;
      /** Character and Object and Creation */
      function atk(target?: Entity): float;
      /** Character and Object and Creation */
      function base_atk(target?: Entity): float;
      /** Character and Object and Creation */
      function def(target?: Entity): float;
      /** Character and Object and Creation */
      function base_def(target?: Entity): float;
      /** Character and Creation */
      function interrupt_threshold(target?: Entity): float;
      /** Character and Creation */
      function interrupt(target?: Entity): float;
      /** Character and Creation */
      function interrupt_status(target?: Entity): EnumInterruptStatus;
      
      /** Character Only */
      function crit_rate(target?: Entity): float;
      /** Character Only */
      function crit_dmg(target?: Entity): float;
      /** Character Only */
      function heal(target?: Entity): float;
      /** Character Only */
      function incoming_heal(target?: Entity): float;
      /** Character Only */
      function recharge(target?: Entity): float;
      /** Character Only */
      function cd_reduction(target?: Entity): float;
      /** Character Only */
      function shield(target?: Entity): float;
      
      // Object Only
      function pyro_dmg(target?: Entity): float;
      function pyro_res(target?: Entity): float;
      function hydro_dmg(target?: Entity): float;
      function hydro_res(target?: Entity): float;
      function dendro_dmg(target?: Entity): float;
      function dendro_res(target?: Entity): float;
      function electro_dmg(target?: Entity): float;
      function electro_res(target?: Entity): float;
      function anemo_dmg(target?: Entity): float;
      function anemo_res(target?: Entity): float;
      function cryo_dmg(target?: Entity): float;
      function cryo_res(target?: Entity): float;
      function geo_dmg(target?: Entity): float;
      function geo_res(target?: Entity): float;
      function physical_dmg(target?: Entity): float;
      function physical_res(target?: Entity): float;
    }
    
    // ------ entity ------ //
    // is on the field
    function is_on_field(entity: Entity): bool;
    // get all on the field
    function on_field(type: EnumEntityType): List;
    function on_field(prefab: Prefab): List;
    function type(entity: Entity): EnumEntityType;
    
    function pos(entity?: Entity): Vec;
    function rot(entity?: Entity): Vec;
    function front(entity?: Entity): Vec;
    function right(entity?: Entity): Vec;
    function up(entity?: Entity): Vec;
    function children(entity?: Entity): List;
    
    function parent(entity?: Entity): Entity;
    function guid(entity: Entity): GUID;
    function entity(guid: GUID): Entity;
    function faction(entity: Entity): Faction;
    function hostile(f1: Faction, f2: Faction): bool;
    
    function filter(src: List, center: Vec, radius: float): List;
    function filter(src: List, type: EnumEntityType): List;
    function filter(src: List, prefab: Prefab): List;
    function filter(src: List, faction: Faction): List;
    
  }
  
  // ====== Operator Nodes ======
  
  function $(lambda: (...args: any[]) => any): [][];
  
  // 选择分支
  function If(cond: bool | Bool): [][];
  // 选择分支
  function Switch(key: bool | float | int | str | Bool | Float | Int | Str): [][];
  
  // ------ 执行节点函数 ------ //
  // 打印字符串
  function Log(str: str | Str): [][];
  
  // 设置局部变量: SetVal(_local_val, new_val)
  // 设置节点图变量: SetVal(self.val, new_val)
  // 设置自定义变量: SetVal(node.val, new_val)
  // function SetVal<T>( //
  //   val: T,
  //   new_val: T,
  //   target?: Entity,
  //   trigger_event?: bool | Bool,
  // ): [][];
  function SetVal(
    val: int,
    new_val: int,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: float,
    new_val: float,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: bool,
    new_val: bool,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: str,
    new_val: str,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Int,
    new_val: Int,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Float,
    new_val: Float,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Bool,
    new_val: Bool,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Str,
    new_val: Str,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Vec,
    new_val: Vec,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: GUID,
    new_val: GUID,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Entity,
    new_val: Entity,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Prefab,
    new_val: Prefab,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Faction,
    new_val: Faction,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: ConfigId,
    new_val: ConfigId,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: List,
    new_val: List,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Dict,
    new_val: Dict,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  function SetVal(
    val: Struct,
    new_val: Struct,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  
  // 有限循环 (from <= i <= to)
  function Loop(
    from: int,
    to: int,
    id: string,
  ): [i: int][];
  // 列表迭代循环
  function ForEach(list: List): [item: SysAllTypes][];
  // 对列表插入值
  function Insert(list: List, index: int | Int, val: SysAllTypes): [][];
  // 对列表修改值
  function Modify(list: List, index: int | Int, val: SysAllTypes): [][];
  // 对列表移除值
  function Remove(list: List, index: int | Int): [][];
  // 对列表移除值
  function Sort(list: List, is_increase?: bool | Bool): [][];
  // 拼接列表
  function Concat(target: List, src: List): [][];
  // 清除列表
  function Clear(list: List): [][];
  
  // 创建实体
  function NewEntity(guid: GUID, tags?: List): [][];
  // 创建元件
  function NewPrefab(
    id: Prefab,
    pos?: Vec,
    rot?: Vec,
    level?: int | Int,
    use_level?: bool | Bool,
    parent?: Entity,
    tags?: List,
  ): [entity: Entity][];
  // 创建元件组
  function NewPrefabs(
    idex: int | Int,
    pos?: Vec,
    rot?: Vec,
    level?: int | Int,
    use_level?: bool | Bool,
    parent?: Entity,
    tags?: List,
  ): [entities: List][];
  // 销毁实体: RemoveEntity(target, true)
  // 移除实体: RemoveEntity(target, false)
  function RemoveEntity(target: Entity, is_destroy?: bool | Bool): [][];
  // 激活/关闭模型显示
  function ModelDisplay(target: Entity, display: bool | Bool): [][];
  
  // 结算关卡
  function Complete(): [][];
  
  // 传送玩家
  function Teleport(player: Entity, pos?: Vec, rot?: Vec): [][];
  // 复苏角色
  // 复苏玩家所有角色
  function Revive(player: Entity): [][];
  // 激活复苏点/注销复苏点: SetRevive(p, enable=true/false, point=id);
  // 允许/禁止玩家复苏: SetRevive(p, enable=true/false)
  // 设置玩家剩余复苏次数: SetRevive(p, left=count)
  // 设置玩家复苏耗时: SetRevive(p, duration=t)
  function SetRevive(
    player: Entity,
    enable?: bool | Bool,
    duration?: float | Float,
    left?: int | Int,
    point?: int | Int,
  ): [][];
  // 击倒玩家所有角色
  function Kill(player: Entity): [][];
  
  // 激活/关闭额外碰撞 SetCollision(e, true/false)
  // 激活/关闭额外碰撞可攀爬性 SetCollision(e, true/false, id=i, is_climb=true)
  // 激活/关闭原生碰撞  SetCollision(e, true/false)
  // 激活/关闭原生碰撞可攀爬性 SetCollision(e, true/false, is_climb=true)
  function SetCollision(
    target: Entity,
    enable: bool | Bool,
    id?: int | Int,
    is_climb?: bool | Bool,
  ): [][];
  // 激活/关闭碰撞触发器
  function SetCollisionTrigger(
    target: Entity,
    enable: bool | Bool,
    id?: int | Int,
  ): [][];
  
  // 转发事件
  function ForwardTrigger(target: Entity): [][];
  
  // 设置当前环境时间(立即切换环境时间到指定小时，参数需要是0~24之间的浮点数值)
  function SetTime(hour: float | Float): [][];
  // 设置环境时间流逝速度(min/second, 0~60)
  function SetTimeSpeed(minutes: float | Float): [][];
  
  
  // ====== Trigger Nodes ======
  
  // ------ 系统事件函数 ------ //
  // 注意, 一些重要参数的位置被前置了, 方便直接填入/读取
  
  // 节点图变量变化时
  // function OnVarChange(name?: symbol):
  //   [new_val: TYPE, old_val: TYPE, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: int, old_val: int, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: float, old_val: float, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: bool, old_val: bool, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: str, old_val: str, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Int, old_val: Int, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Float, old_val: Float, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Bool, old_val: Bool, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Str, old_val: Str, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Vec, old_val: Vec, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: GUID, old_val: GUID, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Entity, old_val: Entity, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Prefab, old_val: Prefab, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Faction, old_val: Faction, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: ConfigId, old_val: ConfigId, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: List, old_val: List, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Dict, old_val: Dict, name: string, src: Entity, src_guid: GUID][];
  function OnVarChange(
    name?: symbol,
  ): [new_val: Struct, old_val: Struct, name: string, src: Entity, src_guid: GUID][];
  
  // 实体创建时
  function OnCreate(): [src: Entity, src_guid: GUID][];
  // 实体销毁时(仅在关卡实体上触发)
  function OnDestroy(): [
    src: Entity,
    src_guid: GUID,
    pos: Vec,
    dir: Vec,
    damage_src: Entity,
    snapshot: Entity,
    type: EnumEntityType,
    parent: Entity,
  ][];
  
  // 角色倒下时(角色实体上的节点图可以触发该事件)
  function OnDeath(): [
    character: Entity,
    cause: EnumDeathCause,
    damage_src: Entity,
  ][];
  // 角色复苏时(角色实体上的节点图可以触发该事件)
  function OnRevive(): [character: Entity][];
  // 玩家传送完成时
  function OnTeleport(): [character: Entity, character_guid: GUID][];
  
  // 进入碰撞触发器时
  function OnCollision(): [
    src: Entity,
    src_guid: GUID,
    trigger_id: int,
    entity: Entity,
    entity_guid: GUID,
  ][];
  // 离开碰撞触发器时
  function OnExitCollision(): [
    src: Entity,
    src_guid: GUID,
    trigger_id: int,
    entity: Entity,
    entity_guid: GUID,
  ][];
  
  // 基础运动器停止时
  function OnMotionFinish(): [name: string, src: Entity, src_guid: GUID][];
  // 路径到达路点时
  function OnPathFinish(): [
    name: string,
    point_index: int,
    src: Entity,
    src_guid: GUID,
  ][];
  
  // 命中检测触发时
  function OnHit(): [
    target: Entity,
    pos: Vec,
    is_hitbox: boolean,
    src: Entity,
    src_guid: GUID,
  ][];
  
  // 定时器触发时
  function OnTimer(name: string): [
    name: string,
    index: int,
    i: int,
    src: Entity,
    src_guid: GUID,
  ][];
  // 全局计时器触发时
  function Timer(): [name: string, src: Entity, src_guid: GUID][];
  
  // 界面控件组触发时(只有触发交互的玩家节点图可以获取)
  function OnUI(): [id: int, group_id: int, src: Entity, src_guid: GUID][];
  // 选项卡选中时
  function OnTab(): [id: int, selector: Entity, src: Entity, src_guid: GUID][];
  
  // 监听信号
  function Signal(
    name: string,
  ): [...params: any[], sender: Entity, src: Entity, src_guid: GUID][];
  
  
  interface Array<T> extends ExecFunctions {
    /** 修改索引签名返回类型 */
    [index: string | float | symbol]: [][];
    /** 分支选择 */
    (...cases: (string | float | null | boolean)[]): [][];
  }

  interface Object extends ExecFunctions {
  }

  const Branch : any[][];
  // ====== End of Global ======
}

// ====== Operator Nodes Helper ======
interface ExecFunctions {
  $(lambda: (...args: any[]) => any): [][];
  
  // 选择分支
  If(cond: bool | Bool): [][];
  // 选择分支
  Switch(key: bool | float | int | str | Bool | Float | Int | Str): [][];
  
  // ------ 执行节点函数 ------ //
  // 打印字符串
  Log(str: str | Str): [][];
  
  // 设置局部变量: SetVal(_local_val, new_val)
  // 设置节点图变量: SetVal(self.val, new_val)
  // 设置自定义变量: SetVal(node.val, new_val)
  // function SetVal<T>( //
  //   val: T,
  //   new_val: T,
  //   target?: Entity,
  //   trigger_event?: bool | Bool,
  // ): [][];
  SetVal(
    val: int,
    new_val: int,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: float,
    new_val: float,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: bool,
    new_val: bool,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: str,
    new_val: str,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Int,
    new_val: Int,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Float,
    new_val: Float,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Bool,
    new_val: Bool,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Str,
    new_val: Str,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Vec,
    new_val: Vec,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: GUID,
    new_val: GUID,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Entity,
    new_val: Entity,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Prefab,
    new_val: Prefab,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Faction,
    new_val: Faction,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: ConfigId,
    new_val: ConfigId,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: List,
    new_val: List,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Dict,
    new_val: Dict,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  SetVal(
    val: Struct,
    new_val: Struct,
    target?: Entity,
    trigger_event?: bool | Bool,
  ): [][];
  
  // 有限循环 (from <= i <= to)
  Loop(
    from: int,
    to: int,
    id: string,
  ): [i: int][];
  // 列表迭代循环
  ForEach(list: List): [item: SysAllTypes][];
  // 对列表插入值
  Insert(list: List, index: int | Int, val: SysAllTypes): [][];
  // 对列表修改值
  Modify(list: List, index: int | Int, val: SysAllTypes): [][];
  // 对列表移除值
  Remove(list: List, index: int | Int): [][];
  // 对列表移除值
  Sort(list: List, is_increase?: bool | Bool): [][];
  // 拼接列表
  Concat(target: List, src: List): [][];
  // 清除列表
  Clear(list: List): [][];
  
  // 创建实体
  NewEntity(guid: GUID, tags?: List): [][];
  // 创建元件
  NewPrefab(
    id: Prefab,
    pos?: Vec,
    rot?: Vec,
    level?: int | Int,
    use_level?: bool | Bool,
    parent?: Entity,
    tags?: List,
  ): [entity: Entity][];
  // 创建元件组
  NewPrefabs(
    idex: int | Int,
    pos?: Vec,
    rot?: Vec,
    level?: int | Int,
    use_level?: bool | Bool,
    parent?: Entity,
    tags?: List,
  ): [entities: List][];
  // 销毁实体: RemoveEntity(target, true)
  // 移除实体: RemoveEntity(target, false)
  RemoveEntity(target: Entity, is_destroy?: bool | Bool): [][];
  // 激活/关闭模型显示
  ModelDisplay(target: Entity, display: bool | Bool): [][];
  
  // 结算关卡
  Complete(): [][];
  
  // 传送玩家
  Teleport(player: Entity, pos?: Vec, rot?: Vec): [][];
  // 复苏角色
  // 复苏玩家所有角色
  Revive(player: Entity): [][];
  // 激活复苏点/注销复苏点: SetRevive(p, enable=true/false, point=id);
  // 允许/禁止玩家复苏: SetRevive(p, enable=true/false)
  // 设置玩家剩余复苏次数: SetRevive(p, left=count)
  // 设置玩家复苏耗时: SetRevive(p, duration=t)
  SetRevive(
    player: Entity,
    enable?: bool | Bool,
    duration?: float | Float,
    left?: int | Int,
    point?: int | Int,
  ): [][];
  // 击倒玩家所有角色
  Kill(player: Entity): [][];
  
  // 激活/关闭额外碰撞 SetCollision(e, true/false)
  // 激活/关闭额外碰撞可攀爬性 SetCollision(e, true/false, id=i, is_climb=true)
  // 激活/关闭原生碰撞  SetCollision(e, true/false)
  // 激活/关闭原生碰撞可攀爬性 SetCollision(e, true/false, is_climb=true)
  SetCollision(
    target: Entity,
    enable: bool | Bool,
    id?: int | Int,
    is_climb?: bool | Bool,
  ): [][];
  // 激活/关闭碰撞触发器
  SetCollisionTrigger(
    target: Entity,
    enable: bool | Bool,
    id?: int | Int,
  ): [][];
  
  // 转发事件
  ForwardTrigger(target: Entity): [][];
  
  // 设置当前环境时间(立即切换环境时间到指定小时，参数需要是0~24之间的浮点数值)
  SetTime(hour: float | Float): [][];
  // 设置环境时间流逝速度(min/second, 0~60)
  SetTimeSpeed(minutes: float | Float): [][];
  
}
