export const data = [
  // ==============================================================================
  // ============================= 客户端节点图可用节点 =============================
  // ==============================================================================

  // ───────────────────────────── 99-客户端事件节点 ─────────────────────────────
  // 事件节点//<隐藏>客户端节点自带
  {
    id: "event.graphStart",
    displayName: "节点图开始",
    displayNameEN: "Node Graph Begins",
    officialID: 200042,
    category: "事件节点/<隐藏>客户端节点自带",
    kind: "event",
    ports: [{ id: "flowOut", label: "事件", kind: "flow-out" }],
  },
  // 流程控制节点/<隐藏>客户端节点自带
  {
    id: "flow.graphEndBoolean",
    displayName: "节点图结束（布尔型）",
    displayNameEN: "Node Graph End (Boolean)",
    officialID: 200000,
    category: "流程控制节点/<隐藏>客户端节点自带",
    kind: "flow-control",
    ports: [
      {
        id: "result",
        label: "输出结果（布尔型）",
        kind: "data-in",
        valueType: "bool",
      },
    ],
  },
  {
    id: "flow.graphEndInteger",
    displayName: "节点图结束（整数）",
    displayNameEN: "Node Graph End (Integer)",
    officialID: 0,
    category: "流程控制节点/<隐藏>客户端节点自带",
    kind: "flow-control",
    ports: [
      {
        id: "result",
        label: "输出结果（整数）",
        kind: "data-in",
        valueType: "int",
      },
    ],
  },
  // 查询节点
  // ───────────────────────────── 01-列表相关 ─────────────────────────────
  // 查询节点/列表相关
  {
    id: "client.query.list.getValue",
    displayName: "获取列表对应值",
    displayNameEN: "Get Corresponding Value From List",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [
      { id: "index", label: "序号", kind: "data-in", valueType: "int" },
      { id: "dataList", label: "数据列表", kind: "data-in", valueType: "list" },
      { id: "result", label: "结果", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.query.list.length",
    displayName: "获取列表长度",
    displayNameEN: "Get List Length",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [
      {
        id: "inputList",
        label: "输入列表",
        kind: "data-in",
        valueType: "list",
      },
      { id: "length", label: "长度", kind: "data-out", valueType: "int" },
    ],
  },
  {
    id: "client.query.list.max",
    displayName: "获取列表最大值",
    displayNameEN: "Get Maximum Value From List",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [
      { id: "list", label: "列表", kind: "data-in", valueType: "list" },
      { id: "maxValue", label: "最大值", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.query.list.min",
    displayName: "获取列表最小值",
    displayNameEN: "Get Minimum Value From List",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [
      { id: "list", label: "列表", kind: "data-in", valueType: "list" },
      { id: "minValue", label: "最小值", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.query.raycast.filterList",
    displayName: "获取射线筛选类型列表",
    displayNameEN: "Get Ray Filter Type List",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [{ id: "list", label: "列表", kind: "data-out", valueType: "list" }],
  },
  {
    id: "client.query.entity.typeList",
    displayName: "获取实体类型列表",
    displayNameEN: "Get Entity Type List",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [{ id: "list", label: "列表", kind: "data-out", valueType: "list" }],
  },
  {
    id: "client.query.list.contains",
    displayName: "列表是否包含该值",
    displayNameEN: "List Includes This Value",
    officialID: 0,
    category: "查询节点/列表相关",
    kind: "query",
    ports: [
      { id: "value", label: "值", kind: "data-in", valueType: "any" },
      { id: "list", label: "列表", kind: "data-in", valueType: "list" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },

  // ───────────────────────────── 02-自定义变量 ─────────────────────────────
  // 查询节点/自定义变量
  {
    id: "client.query.customVariable.get",
    displayName: "获取自定义变量",
    displayNameEN: "Get Custom Variable",
    officialID: 0,
    category: "查询节点/自定义变量",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "variableName",
        label: "变量名",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "variableValue",
        label: "变量值",
        kind: "data-out",
        valueType: "any",
      },
    ],
  },

  // ───────────────────────────── 03-预设状态 ─────────────────────────────
  // 查询节点/预设状态
  {
    id: "client.query.presetState.get",
    displayName: "获取预设状态",
    displayNameEN: "Get Preset Status",
    officialID: 0,
    category: "查询节点/预设状态",
    kind: "query",
    ports: [
      { id: "entity", label: "实体", kind: "data-in", valueType: "entity" },
      {
        id: "presetIndex",
        label: "预设状态索引",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "presetValue",
        label: "预设状态值",
        kind: "data-out",
        valueType: "int",
      },
    ],
  },

  // ───────────────────────────── 04-实体相关 ─────────────────────────────
  // 查询节点/实体相关
  {
    id: "client.query.entity.isPresent",
    displayName: "查询实体是否在场",
    displayNameEN: "Query If Entity Is on the Field",
    officialID: 200103,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "isPresent",
        label: "是否在场",
        kind: "data-out",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.query.entity.getAttackTarget",
    displayName: "获取单位攻击目标",
    displayNameEN: "Get Unit Attack Target",
    officialID: 200035,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      {
        id: "unitEntity",
        label: "单位实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "attackTargetEntity",
        label: "攻击目标实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.query.entity.getSocketPosition",
    displayName: "获取目标挂接点位置",
    displayNameEN: "Get Target Attachment Point Location",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "attachmentName",
        label: "挂接点名称",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "attachmentPosition",
        label: "挂接点位置",
        kind: "data-out",
        valueType: "vector3",
      },
    ],
  },
  {
    id: "client.query.entity.getSocketRotation",
    displayName: "获取目标挂接点旋转",
    displayNameEN: "Get Target Attachment Point Rotation",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "attachmentName",
        label: "挂接点名称",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "attachmentRotation",
        label: "挂接点旋转",
        kind: "data-out",
        valueType: "vector3",
      },
    ],
  },
  {
    id: "client.query.getTargetEntity",
    displayName: "获取目标实体",
    displayNameEN: "Get Target Entity",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.query.getEntityType",
    displayName: "获取实体的类型",
    displayNameEN: "Get Entity‘s Type",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "entityType",
        label: "实体类型",
        kind: "data-out",
        valueType: "enum",
      },
    ],
  },
  {
    id: "client.query.getEntityPosition",
    displayName: "获取实体位置",
    displayNameEN: "Get Entity Location",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      { id: "entity", label: "实体", kind: "data-in", valueType: "entity" },
      { id: "position", label: "位置", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.query.getEntityRotation",
    displayName: "获取实体旋转",
    displayNameEN: "Get Entity Rotation",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      { id: "entity", label: "实体", kind: "data-in", valueType: "entity" },
      { id: "rotation", label: "旋转", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.query.getSelfEntity",
    displayName: "获取自身实体",
    displayNameEN: "Get Self Entity",
    officialID: 200033,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      { id: "self", label: "自身实体", kind: "data-out", valueType: "entity" },
    ],
  },
  {
    id: "client.query.filterEntitiesInBox",
    displayName: "筛选方形范围内的实体列表",
    displayNameEN: "Filter Entity List Within Square Range",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      { id: "width", label: "宽度", kind: "data-in", valueType: "float" },
      { id: "height", label: "高度", kind: "data-in", valueType: "float" },
      { id: "length", label: "长度", kind: "data-in", valueType: "float" },
      {
        id: "center",
        label: "中心位置",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "limit", label: "筛选数量上限", kind: "data-in", valueType: "int" },
      { id: "rule", label: "筛选规则", kind: "data-in", valueType: "enum" },
      { id: "result", label: "筛选结果", kind: "data-out", valueType: "list" },
    ],
  },
  {
    id: "client.query.filterEntitiesInSphere",
    displayName: "筛选球体范围内的实体列表",
    displayNameEN: "Filter Entity List Within Spherical Range",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      { id: "radius", label: "半径", kind: "data-in", valueType: "float" },
      {
        id: "center",
        label: "中心位置",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "limit", label: "筛选数量上限", kind: "data-in", valueType: "int" },
      { id: "rule", label: "筛选规则", kind: "data-in", valueType: "enum" },
      { id: "result", label: "筛选结果", kind: "data-out", valueType: "list" },
    ],
  },
  {
    id: "client.query.findEntityByGuid",
    displayName: "以GUID查询实体",
    displayNameEN: "Query Entity by GUID",
    officialID: 0,
    category: "查询节点/实体相关",
    kind: "query",
    ports: [
      { id: "guid", label: "GUID", kind: "data-in", valueType: "guid" },
      { id: "entity", label: "实体", kind: "data-out", valueType: "entity" },
    ],
  },

  // ───────────────────────────── 05-阵营相关 ─────────────────────────────
  // 查询节点/阵营相关
  {
    id: "client.query.getEntityCamp",
    displayName: "查询实体阵营",
    displayNameEN: "Query Entity Faction",
    officialID: 0,
    category: "查询节点/阵营相关",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      { id: "camp", label: "阵营", kind: "data-out", valueType: "camp" },
    ],
  },
  {
    id: "client.query.campsAreHostile",
    displayName: "查询阵营是否敌对",
    displayNameEN: "Query If Faction Is Hostile",
    officialID: 0,
    category: "查询节点/阵营相关",
    kind: "query",
    ports: [
      { id: "camp1", label: "阵营1", kind: "data-in", valueType: "camp" },
      { id: "camp2", label: "阵营2", kind: "data-in", valueType: "camp" },
      {
        id: "isHostile",
        label: "是否敌对",
        kind: "data-out",
        valueType: "bool",
      },
    ],
  },

  // ───────────────────────────── 06-玩家与角色相关 ─────────────────────────────
  // 查询节点/玩家与角色相关
  {
    id: "client.query.player.isSelfInCombat",
    displayName: "查询自身是否已入战",
    displayNameEN: "Query If Self Is in Combat",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      {
        id: "isInCombat",
        label: "是否入战",
        kind: "data-out",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.query.player.getCurrentCharacter",
    displayName: "获取当前角色",
    displayNameEN: "Get Current Character",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      {
        id: "characterEntity",
        label: "角色实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.query.character.getOwnerPlayer",
    displayName: "获取角色归属的玩家实体",
    displayNameEN: "Get Player Entity to Which the Character Belongs",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      {
        id: "characterEntity",
        label: "角色实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "ownerPlayerEntity",
        label: "所属玩家实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.query.player.listPresent",
    displayName: "获取在场玩家实体列表",
    displayNameEN: "Get List of Player Entities on the Field",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      {
        id: "playerEntities",
        label: "玩家实体列表",
        kind: "data-out",
        valueType: "list",
      },
    ],
  },
  {
    id: "client.query.player.getCharacter",
    displayName: "获取指定玩家的角色实体",
    displayNameEN: "Get Character Entity of Specified Player",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      {
        id: "playerEntity",
        label: "玩家实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "characterEntity",
        label: "角色实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.query.entityToGuid",
    displayName: "以实体查询GUID",
    displayNameEN: "Query GUID by Entity",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      { id: "entity", label: "实体", kind: "data-in", valueType: "entity" },
      { id: "guid", label: "GUID", kind: "data-out", valueType: "guid" },
    ],
  },
  {
    id: "client.query.getInputDeviceType",
    displayName: "获得玩家客户端输入设备类型",
    displayNameEN: "Get Player Client Input Device Type",
    officialID: 0,
    category: "查询节点/玩家与角色相关",
    kind: "query",
    ports: [
      {
        id: "inputDeviceType",
        label: "输入设备类型",
        kind: "data-out",
        valueType: "enum",
      },
    ],
  },

  // ───────────────────────────── 07-标签 ─────────────────────────────
  // 查询节点/标签
  {
    id: "client.query.unitTagEntities",
    displayName: "获取单位标签的实体列表",
    displayNameEN: "Get Entity List by Unit Tag",
    officialID: 0,
    category: "查询节点/标签",
    kind: "query",
    ports: [
      {
        id: "unitTagIndex",
        label: "单位标签索引",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "entities",
        label: "实体列表",
        kind: "data-out",
        valueType: "list",
      },
    ],
  },
  {
    id: "client.query.entityUnitTagIndexes",
    displayName: "获取实体的单位标签列表",
    displayNameEN: "Get Entity's Unit Tag List",
    officialID: 0,
    category: "查询节点/标签",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      { id: "indexes", label: "列表", kind: "data-out", valueType: "list" },
    ],
  },

  // ───────────────────────────── 08-通用 ─────────────────────────────
  // 查询节点/通用
  {
    id: "client.query.getLocalVariable",
    displayName: "获取局部变量",
    displayNameEN: "Get Local Variable",
    officialID: 0,
    category: "查询节点/通用",
    kind: "query",
    ports: [
      {
        id: "variableName",
        label: "变量名",
        kind: "data-in",
        valueType: "string",
      },
      { id: "value", label: "变量值", kind: "data-out", valueType: "any" },
    ],
  },

  // ───────────────────────────── 09-自定义仇恨 ─────────────────────────────
  // 查询节点/自定义仇恨
  {
    id: "client.query.isEntityInCombat",
    displayName: "查询指定实体是否入战",
    displayNameEN: "Query if Specified Entity is in Combat",
    officialID: 0,
    category: "查询节点/自定义仇恨",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "isInCombat",
        label: "是否入战",
        kind: "data-out",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.query.entityHateList",
    displayName: "获取指定实体的仇恨列表",
    displayNameEN: "Get the Aggro List of the Specified Entity",
    officialID: 0,
    category: "查询节点/自定义仇恨",
    kind: "query",
    ports: [
      {
        id: "specifiedEntity",
        label: "指定实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "hateList",
        label: "仇恨列表",
        kind: "data-out",
        valueType: "list",
      },
    ],
  },
  {
    id: "client.query.entityHateTarget",
    displayName: "获取指定实体的仇恨目标",
    displayNameEN: "Get the Aggro Target of the Specified Entity",
    officialID: 0,
    category: "查询节点/自定义仇恨",
    kind: "query",
    ports: [
      {
        id: "specifiedEntity",
        label: "指定实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "hateTarget",
        label: "仇恨目标",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },

  // ───────────────────────────── 10-触发器 ─────────────────────────────
  // 查询节点/触发器
  {
    id: "client.query.getEntitiesInCollisionTrigger",
    displayName: "获取碰撞触发器内所有实体",
    displayNameEN: "Get All Entities Within the Collision Trigger",
    officialID: 0,
    category: "查询节点/触发器",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "triggerIndex",
        label: "触发器序号",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "entities",
        label: "实体列表",
        kind: "data-out",
        valueType: "list",
      },
    ],
  },

  // ───────────────────────────── 11-射线 ─────────────────────────────
  // 查询节点/射线
  {
    id: "client.query.getRaycastResult",
    displayName: "获取射线检测结果",
    displayNameEN: "Get Ray Detection Result",
    officialID: 0,
    category: "查询节点/射线",
    kind: "query",
    ports: [
      {
        id: "caster",
        label: "检测发起者实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "origin",
        label: "出射位置",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "direction",
        label: "出射方向",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "maxLength",
        label: "射线最大长度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "campFilter",
        label: "阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "entityTypeFilter",
        label: "实体类型筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitLayerFilter",
        label: "命中层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitPosition",
        label: "命中位置",
        kind: "data-out",
        valueType: "vector3",
      },
      {
        id: "hitEntity",
        label: "命中实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.query.raycast.getResult",
    displayName: "获取射线检测结果",
    displayNameEN: "Get Ray Detection Result",
    officialID: 0,
    category: "查询节点/射线",
    kind: "query",
    ports: [
      {
        id: "origin",
        label: "出射位置",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "direction",
        label: "出射方向",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "maxDistance",
        label: "射线最大长度",
        kind: "data-in",
        valueType: "float",
      },

      {
        id: "hitPosition",
        label: "命中位置",
        kind: "data-out",
        valueType: "vector3",
      },
      {
        id: "hitEntity",
        label: "命中实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },

  // ───────────────────────────── 12-扫描 ─────────────────────────────
  // 查询节点/扫描
  {
    id: "client.query.scanAllValidObjects",
    displayName: "获取扫描组件可扫描的所有合法对象",
    displayNameEN: "Get All Valid Entities That Are Scannable by Scan Component",
    officialID: 0,
    category: "查询节点/扫描",
    kind: "query",
    ports: [
      { id: "objects", label: "对象列表", kind: "data-out", valueType: "list" },
    ],
  },
  {
    id: "client.query.scanCurrentHit",
    displayName: "获取扫描组件当前扫描到的实体",
    displayNameEN: "Get Entity Currently Scanned by Scan Component",
    officialID: 0,
    category: "查询节点/扫描",
    kind: "query",
    ports: [
      {
        id: "entity",
        label: "对应实体",
        kind: "data-out",
        valueType: "entity",
      },
      {
        id: "scanTagConfigId",
        label: "扫描标签配置ID",
        kind: "data-out",
        valueType: "configId",
      },
    ],
  },
  {
    id: "client.query.getEntityScanTag",
    displayName: "获取实体当前生效的扫描标签",
    displayNameEN: "Get Entity's Current Active Scan Tags",
    officialID: 0,
    category: "查询节点/扫描",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "scanTagConfigId",
        label: "扫描标签配置ID",
        kind: "data-out",
        valueType: "configId",
      },
    ],
  },
  {
    id: "client.query.getEntityScanState",
    displayName: "获取实体扫描状态",
    displayNameEN: "Get Entity's Scan Status",
    officialID: 0,
    category: "查询节点/扫描",
    kind: "query",
    ports: [
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "scanState",
        label: "扫描状态",
        kind: "data-out",
        valueType: "enum",
      },
    ],
  },

  // 运算节点
  // ───────────────────────────── 00-通用 ─────────────────────────────
  // 运算节点/通用
  {
    id: "client.math.enumMatch",
    displayName: "枚举匹配",
    displayNameEN: "Enumeration Match",
    officialID: 0,
    category: "运算节点/通用",
    kind: "math",
    ports: [
      { id: "enum1", label: "枚举1", kind: "data-in", valueType: "any" },
      { id: "enum2", label: "枚举2", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.isEqual",
    displayName: "是否相等",
    displayNameEN: "Equal",
    officialID: 0,
    category: "运算节点/通用",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.typeCast",
    displayName: "数据类型转换",
    displayNameEN: "Data Type Conversion",
    officialID: 0,
    category: "运算节点/通用",
    kind: "math",
    ports: [
      { id: "input", label: "输入", kind: "data-in", valueType: "any" },
      {
        id: "converted",
        label: "转换结果",
        kind: "data-out",
        valueType: "any",
      },
    ],
  },

  // ───────────────────────────── 01-数学 ─────────────────────────────
  // 运算节点/数学
  {
    id: "client.math.vector3.split",
    displayName: "拆分三维向量",
    displayNameEN: "Split 3D Vector",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector",
        label: "三维向量",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "x", label: "X分量", kind: "data-out", valueType: "float" },
      { id: "y", label: "Y分量", kind: "data-out", valueType: "float" },
      { id: "z", label: "Z分量", kind: "data-out", valueType: "float" },
    ],
  },

  {
    id: "client.math.math.multiply",
    displayName: "乘法运算",
    displayNameEN: "Multiplication",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.math.math.divide",
    displayName: "除法运算",
    displayNameEN: "Division",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.math.sin",
    displayName: "正弦函数",
    displayNameEN: "Sine Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "radian", label: "弧度", kind: "data-in", valueType: "float" },
      { id: "result", label: "结果", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.cos",
    displayName: "余弦函数",
    displayNameEN: "Cosine Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "radian", label: "弧度", kind: "data-in", valueType: "float" },
      { id: "result", label: "结果", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.tan",
    displayName: "正切函数",
    displayNameEN: "Tangent Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "radian", label: "弧度", kind: "data-in", valueType: "float" },
      { id: "result", label: "结果", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.degToRad",
    displayName: "角度转弧度",
    displayNameEN: "Degrees to Radians",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "degree", label: "角度", kind: "data-in", valueType: "float" },
      { id: "radian", label: "弧度", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.radToDeg",
    displayName: "弧度转角度",
    displayNameEN: "Radians to Degrees",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "radian", label: "弧度", kind: "data-in", valueType: "float" },
      { id: "degree", label: "角度", kind: "data-out", valueType: "float" },
    ],
  },

  {
    id: "client.math.arcCos",
    displayName: "反余弦函数",
    displayNameEN: "Arccosine Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "input", label: "输入", kind: "data-in", valueType: "float" },
      { id: "radians", label: "弧度", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.arcTan",
    displayName: "反正切函数",
    displayNameEN: "Arctangent Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "input", label: "输入", kind: "data-in", valueType: "float" },
      { id: "radians", label: "弧度", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.arcSin",
    displayName: "反正弦函数",
    displayNameEN: "Arcsine Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "input", label: "输入", kind: "data-in", valueType: "float" },
      { id: "radians", label: "弧度", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.directionVectorToRotation",
    displayName: "方向向量转旋转",
    displayNameEN: "Direction Vector to Rotation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "forward",
        label: "向前向量",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "up", label: "向上向量", kind: "data-in", valueType: "vector3" },
      { id: "rotation", label: "旋转", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.math.randomInRange",
    displayName: "获取随机数",
    displayNameEN: "Get Random Number",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "min", label: "下限", kind: "data-in", valueType: "any" },
      { id: "max", label: "上限", kind: "data-in", valueType: "any" },
      { id: "value", label: "随机数", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.math.add",
    displayName: "加法运算",
    displayNameEN: "Addition",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.math.subtract",
    displayName: "减法运算",
    displayNameEN: "Subtraction",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.math.abs",
    displayName: "绝对值运算",
    displayNameEN: "Absolute Value Operation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "input", label: "输入", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "any" },
    ],
  },
  {
    id: "client.math.logicalNot",
    displayName: "逻辑非运算",
    displayNameEN: "Logical NOT Operation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "cond", label: "条件", kind: "data-in", valueType: "bool" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.logicalOr",
    displayName: "逻辑或运算",
    displayNameEN: "Logical OR Operation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "条件1", kind: "data-in", valueType: "bool" },
      { id: "b", label: "条件2", kind: "data-in", valueType: "bool" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.logicalXor",
    displayName: "逻辑异或运算",
    displayNameEN: "Logical XOR Operation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "条件1", kind: "data-in", valueType: "bool" },
      { id: "b", label: "条件2", kind: "data-in", valueType: "bool" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.logicalAnd",
    displayName: "逻辑与运算",
    displayNameEN: "Logical AND Operation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "条件1", kind: "data-in", valueType: "bool" },
      { id: "b", label: "条件2", kind: "data-in", valueType: "bool" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.normalizeVector3",
    displayName: "三维向量归一化",
    displayNameEN: "3D Vector Normalization",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector",
        label: "三维向量",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "result", label: "结果", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.math.addVector3",
    displayName: "三维向量加法",
    displayNameEN: "3D Vector Addition",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector1",
        label: "三维向量1",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "vector2",
        label: "三维向量2",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "sum", label: "计算结果", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.math.angleBetweenVector3",
    displayName: "三维向量夹角",
    displayNameEN: "3D Vector Angle",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector1",
        label: "三维向量1",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "vector2",
        label: "三维向量2",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "angleDegrees",
        label: "夹角角度",
        kind: "data-out",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.math.subtractVector3",
    displayName: "三维向量减法",
    displayNameEN: "3D Vector Subtraction",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector1",
        label: "三维向量1",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "vector2",
        label: "三维向量2",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "diff", label: "计算结果", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.math.vector3Length",
    displayName: "三维向量模运算",
    displayNameEN: "3D Vector Modulo Operation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector",
        label: "三维向量",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "result", label: "结果", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.dotVector3",
    displayName: "三维向量内积",
    displayNameEN: "3D Vector Dot Product",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector1",
        label: "三维向量1",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "vector2",
        label: "三维向量2",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "dot", label: "计算结果", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.scaleVector3",
    displayName: "三维向量缩放",
    displayNameEN: "3D Vector Zoom",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "scale", label: "缩放倍率", kind: "data-in", valueType: "float" },
      {
        id: "vector",
        label: "三维向量",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "result", label: "结果", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.math.crossVector3",
    displayName: "三维向量外积",
    displayNameEN: "3D Vector Cross Product",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector1",
        label: "三维向量1",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "vector2",
        label: "三维向量2",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "cross",
        label: "计算结果",
        kind: "data-out",
        valueType: "vector3",
      },
    ],
  },
  {
    id: "client.math.rotateVector3",
    displayName: "三维向量旋转",
    displayNameEN: "3D Vector Rotation",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      {
        id: "vector",
        label: "被旋转的三维向量",
        kind: "data-in",
        valueType: "vector3",
      },
      { id: "rotation", label: "旋转", kind: "data-in", valueType: "vector3" },
      { id: "result", label: "结果", kind: "data-out", valueType: "vector3" },
    ],
  },
  {
    id: "client.math.greaterThan",
    displayName: "是否大于",
    displayNameEN: "Greater Than",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.greaterOrEqual",
    displayName: "是否大于等于",
    displayNameEN: "Greater Than or Equal To",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.lessThan",
    displayName: "是否小于",
    displayNameEN: "Less Than",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.lessOrEqual",
    displayName: "是否小于等于",
    displayNameEN: "Less Than or Equal To",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "a", label: "", kind: "data-in", valueType: "any" },
      { id: "b", label: "", kind: "data-in", valueType: "any" },
      { id: "result", label: "结果", kind: "data-out", valueType: "bool" },
    ],
  },
  {
    id: "client.math.tan",
    displayName: "正切函数",
    displayNameEN: "Tangent Function",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "radians", label: "弧度", kind: "data-in", valueType: "float" },
      { id: "result", label: "结果", kind: "data-out", valueType: "float" },
    ],
  },
  {
    id: "client.math.makeVector3",
    displayName: "创建三维向量",
    displayNameEN: "Create 3D Vector",
    officialID: 0,
    category: "运算节点/数学",
    kind: "math",
    ports: [
      { id: "x", label: "X分量", kind: "data-in", valueType: "float" },
      { id: "y", label: "Y分量", kind: "data-in", valueType: "float" },
      { id: "z", label: "Z分量", kind: "data-in", valueType: "float" },
      {
        id: "vector",
        label: "三维向量",
        kind: "data-out",
        valueType: "vector3",
      },
    ],
  },

  // ───────────────────────────── 03-列表 ─────────────────────────────
  // 运算节点/列表
  {
    id: "client.math.assembleList",
    displayName: "拼装列表",
    displayNameEN: "Assembly List",
    officialID: 0,
    category: "运算节点/列表",
    kind: "math",
    ports: [
      { id: "params0To99", label: "0~99", kind: "data-in", valueType: "any" },
      { id: "list", label: "列表", kind: "data-out", valueType: "list" },
    ],
  },

  // 执行节点
  // ───────────────────────────── 01-角色技能 ─────────────────────────────
  // 执行节点/角色技能
  {
    id: "client.action.iterateEntities",
    displayName: "遍历实体列表",
    displayNameEN: "Traverse Entity List",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "loopBody", label: "执行", kind: "flow-out" },
      { id: "flowFinish", label: "完成", kind: "flow-out" },
      {
        id: "entityList",
        label: "实体列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "currentEntity",
        label: "当前实体",
        kind: "data-out",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.action.playTimedEffect",
    displayName: "播放限时特效",
    displayNameEN: "Play Timed Effects",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "effectConfigId",
        label: "特效资产配置ID",
        kind: "data-in",
        valueType: "configId",
      },
      { id: "position", label: "位置", kind: "data-in", valueType: "vector3" },
      { id: "rotation", label: "旋转", kind: "data-in", valueType: "vector3" },
      {
        id: "scale",
        label: "缩放倍率",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "playDefaultSfx",
        label: "是否播放默认音效",
        kind: "data-in",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.action.fireProjectileAtPoint",
    displayName: "定点发射投射物",
    displayNameEN: "Fixed-Point Projectile Launch",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "projectileComponentId",
        label: "投射物的元件ID",
        kind: "data-in",
        valueType: "componentId",
      },
      {
        id: "spawnPosition",
        label: "创建位置",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "spawnRotation",
        label: "创建旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "trackingTarget",
        label: "追踪目标",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "projectileCamp",
        label: "投射物阵营",
        kind: "data-in",
        valueType: "camp",
      },
    ],
  },
  {
    id: "client.action.moveToPoint",
    displayName: "定点位移",
    displayNameEN: "Fixed-Point Displacement",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "duration",
        label: "位移时长",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "dampingDuration",
        label: "位移衰减时长",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "speed",
        label: "位移速度",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "targetPosition",
        label: "位移目标位置",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "stopOnCollision",
        label: "碰撞是否终止位移",
        kind: "data-in",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.action.restoreHp",
    displayName: "恢复生命值",
    displayNameEN: "Recover HP",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "healAmount",
        label: "恢复量",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "ignoreHealingAdjustments",
        label: "是否忽略恢复调整效果",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "aggroMultiplier",
        label: "本次治疗的仇恨倍率",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "aggroIncrement",
        label: "本次治疗的仇恨增量",
        kind: "data-in",
        valueType: "int",
        ui: { placeholder: "输入整数" },
      },
    ],
  },
  {
    id: "client.action.cameraRaycastData",
    displayName: "镜头朝向检测数据",
    displayNameEN: "Camera Orientation Detection Data",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "targetType",
        label: "目标类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "origin",
        label: "出射位置",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "minDistance",
        label: "最近距离",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "maxDistance",
        label: "最远距离",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "targetRotation",
        label: "目标旋转",
        kind: "data-out",
        valueType: "vector3",
      },
      {
        id: "targetPosition",
        label: "目标位置",
        kind: "data-out",
        valueType: "vector3",
      },
    ],
  },
  {
    id: "client.action.forceExitAim",
    displayName: "强制退出瞄准状态",
    displayNameEN: "Force Exit Aiming State",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
    ],
  },
  {
    id: "client.action.setSelfAttackTarget",
    displayName: "设置自身攻击目标",
    displayNameEN: "Set Own Attack Target",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "targetEntity",
        label: "目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "instantTurn",
        label: "是否立即转向",
        kind: "data-in",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.action.attackBoxAtPosition",
    displayName: "特定位置打攻击盒",
    displayNameEN: "Trigger Hitbox at Specific Location",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      { id: "position", label: "位置", kind: "data-in", valueType: "vector3" },
      { id: "rotation", label: "旋转", kind: "data-in", valueType: "vector3" },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "attackBoxShape",
        label: "攻击盒类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "boxScale",
        label: "攻击盒为长方体时的缩放",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "sphereRadius",
        label: "攻击盒为球体时的半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorHeight",
        label: "攻击盒为扇形时的高度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorAngle",
        label: "攻击盒为扇形时的扇角度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorRadius",
        label: "攻击盒为扇形时的扇半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorInnerRadius",
        label: "攻击盒为扇形时的内半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorDirection",
        label: "攻击盒为扇形时的检测方向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.rectangularAttackBoxAtPosition",
    displayName: "特定位置打矩形攻击盒",
    displayNameEN: "Trigger Rectangular Hitbox at Specific Location",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      { id: "position", label: "位置", kind: "data-in", valueType: "vector3" },
      { id: "rotation", label: "旋转", kind: "data-in", valueType: "vector3" },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "boxScale",
        label: "攻击盒为长方体时的缩放",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.sphericalAttackBoxAtPosition",
    displayName: "特定位置打球形攻击盒",
    displayNameEN: "Trigger Spherical Hitbox at Specific Location",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      { id: "position", label: "位置", kind: "data-in", valueType: "vector3" },
      { id: "rotation", label: "旋转", kind: "data-in", valueType: "vector3" },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "sphereRadius",
        label: "攻击盒为球体时的半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.sectorAttackBoxAtPosition",
    displayName: "特定位置打扇形攻击盒",
    displayNameEN: "Trigger Sector Hitbox at Specific Location",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      { id: "position", label: "位置", kind: "data-in", valueType: "vector3" },
      { id: "rotation", label: "旋转", kind: "data-in", valueType: "vector3" },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "sectorHeight",
        label: "攻击盒为扇形时的高度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorAngle",
        label: "攻击盒为扇形时的扇角度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorRadius",
        label: "攻击盒为扇形时的扇半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorInnerRadius",
        label: "攻击盒为扇形时的内半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorDirection",
        label: "攻击盒为扇形时的检测方向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.addUnitState",
    displayName: "添加单位状态",
    displayNameEN: "Add Unit Status",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "targetEntity",
        label: "施加目标",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "stackCount",
        label: "层数",
        kind: "data-in",
        valueType: "int",
        ui: { placeholder: "输入整数" },
      },
      {
        id: "stateConfigId",
        label: "单位状态配置ID",
        kind: "data-in",
        valueType: "configId",
      },
    ],
  },
  {
    id: "client.action.notifyServerGraph",
    displayName: "通知服务器节点图",
    displayNameEN: "Notify Server Node Graph",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "str1", label: "字符串1", kind: "data-in", valueType: "string" },
      { id: "str2", label: "字符串2", kind: "data-in", valueType: "string" },
      { id: "str3", label: "字符串3", kind: "data-in", valueType: "string" },
    ],
  },
  {
    id: "client.action.playerTurn",
    displayName: "玩家转向",
    displayNameEN: "Player Turning",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "turnMode", label: "转向模式", kind: "data-in", valueType: "enum" },
    ],
  },
  {
    id: "client.action.playerTurnToDirection",
    displayName: "玩家转向指定朝向",
    displayNameEN: "Player Turns to Face Set Direction",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "direction", label: "朝向", kind: "data-in", valueType: "vector3" },
    ],
  },
  {
    id: "client.action.modifyAttackWeight",
    displayName: "修改攻击权重",
    displayNameEN: "Modify Attack Weight",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "currentTargetWeight",
        label: "当前攻击目标的权重",
        kind: "data-in",
        valueType: "float",
        ui: { placeholder: "输入浮点数" },
      },
      {
        id: "forceSelectOnce",
        label: "是否强制选一次目标",
        kind: "data-in",
        valueType: "bool",
      },
    ],
  },
  {
    id: "client.action.removeUnitState",
    displayName: "移除单位状态",
    displayNameEN: "Remove Unit Status",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "targetEntity",
        label: "移除目标",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "stateConfigId",
        label: "单位状态配置ID",
        kind: "data-in",
        valueType: "configId",
      },
    ],
  },
  {
    id: "client.action.removeCharacterDisturbDevice",
    displayName: "移除指定角色扰动装置",
    displayNameEN: "Remove Specified Character Disruptor Device",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "deviceType",
        label: "扰动装置类型",
        kind: "data-in",
        valueType: "enum",
      },
    ],
  },
  {
    id: "client.action.attackBoxAtSocket",
    displayName: "指定挂接点打攻击盒",
    displayNameEN: "Trigger Hitbox at Specific Location",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "socketName",
        label: "挂接点名称",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "socketOffset",
        label: "挂接点偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "socketRotation",
        label: "挂接点旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "attackBoxShape",
        label: "攻击盒类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "boxScale",
        label: "攻击盒为长方体时的缩放",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "sphereRadius",
        label: "攻击盒为球体时的半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorHeight",
        label: "攻击盒为扇形时的高度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorAngle",
        label: "攻击盒为扇形时的扇角度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorRadius",
        label: "攻击盒为扇形时的扇半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorInnerRadius",
        label: "攻击盒为扇形时的内半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorDirection",
        label: "攻击盒为扇形时的检测方向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.rectangularAttackBoxAtSocket",
    displayName: "指定挂接点打矩形攻击盒",
    displayNameEN: "Trigger Rectangular Hitbox at Specific Attachment Point",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "socketName",
        label: "挂接点名称",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "socketOffset",
        label: "挂接点偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "socketRotation",
        label: "挂接点旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "boxScale",
        label: "攻击盒为长方体时的缩放",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.sphericalAttackBoxAtSocket",
    displayName: "指定挂接点打球形攻击盒",
    displayNameEN: "Trigger Spherical Hitbox at Specific Attachment Point",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "socketName",
        label: "挂接点名称",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "socketOffset",
        label: "挂接点偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "socketRotation",
        label: "挂接点旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "sphereRadius",
        label: "攻击盒为球体时的半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.sectorAttackBoxAtSocket",
    displayName: "指定挂接点扇形打攻击盒",
    displayNameEN: "Trigger Sector Hitbox at Specific Attachment Point",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "campFilter",
        label: "目标阵营筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "socketName",
        label: "挂接点名称",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "socketOffset",
        label: "挂接点偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "socketRotation",
        label: "挂接点旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "damageRatio",
        label: "伤害系数",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "damageOffset",
        label: "伤害增量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "entityTypeFilterList",
        label: "攻击盒实体类型筛选列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "triggerType",
        label: "触发类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitSceneFx",
        label: "命中场景特效",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "sectorHeight",
        label: "攻击盒为扇形时的高度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorAngle",
        label: "攻击盒为扇形时的扇角度",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorRadius",
        label: "攻击盒为扇形时的扇半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorInnerRadius",
        label: "攻击盒为扇形时的内半径",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "sectorDirection",
        label: "攻击盒为扇形时的检测方向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "hitLayerFilter",
        label: "攻击层筛选",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "attackTags",
        label: "攻击标签列表",
        kind: "data-in",
        valueType: "list",
      },
      {
        id: "elementType",
        label: "元素类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "elementAttackEnhance",
        label: "元素攻击强效",
        kind: "data-in",
        valueType: "float",
      },
      { id: "hitType", label: "打击类型", kind: "data-in", valueType: "enum" },
      {
        id: "attackType",
        label: "攻击类型",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "interruptValue",
        label: "打断值",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "absoluteDamage",
        label: "是否是绝对伤害",
        kind: "data-in",
        valueType: "bool",
      },
      { id: "hitFx", label: "命中特效", kind: "data-in", valueType: "int" },
      {
        id: "knockbackDirection",
        label: "受击击退朝向",
        kind: "data-in",
        valueType: "enum",
      },
      {
        id: "suppressFloatingText",
        label: "是否屏蔽伤害跳字",
        kind: "data-in",
        valueType: "bool",
      },
      {
        id: "hitSceneFxOffset",
        label: "命中场景特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxRotation",
        label: "命中场景特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitSceneFxScale",
        label: "命中场景特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "hitFxOffset",
        label: "命中特效偏移",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxRotation",
        label: "命中特效旋转",
        kind: "data-in",
        valueType: "vector3",
      },
      {
        id: "hitFxScale",
        label: "命中特效缩放",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroMultiplier",
        label: "本次攻击的仇恨倍率",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "aggroIncrement",
        label: "本次攻击的仇恨增量",
        kind: "data-in",
        valueType: "int",
      },
      { id: "hitLevel", label: "受击等级", kind: "data-in", valueType: "enum" },
      {
        id: "horizontalImpulse",
        label: "命中水平冲量",
        kind: "data-in",
        valueType: "float",
      },
      {
        id: "verticalImpulse",
        label: "命中垂直冲量",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.resetSkillTarget",
    displayName: "重置技能目标",
    displayNameEN: "Reset Skill Target",
    officialID: 0,
    category: "执行节点/角色技能",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
    ],
  },

  // ───────────────────────────── 02-通用 ─────────────────────────────
  // 执行节点/通用
  {
    id: "client.action.setLocalVariable",
    displayName: "设置局部变量",
    displayNameEN: "Set Local Variable",
    officialID: 0,
    category: "执行节点/通用",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "variableName",
        label: "变量名",
        kind: "data-in",
        valueType: "string",
      },
      {
        id: "variableValue",
        label: "变量值",
        kind: "data-in",
        valueType: "any",
        ui: { accessory: "gear" },
      },
    ],
  },
  {
    id: "client.action.breakLoop",
    displayName: "跳出循环",
    displayNameEN: "Break Loop",
    officialID: 0,
    category: "执行节点/通用",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
    ],
  },
  {
    id: "client.action.loopFinite",
    displayName: "有限循环",
    displayNameEN: "Finite Loop",
    officialID: 0,
    category: "执行节点/通用",
    kind: "action",
    ports: [
      { id: "execIn", label: "执行", kind: "flow-in" },
      { id: "breakIn", label: "跳出循环", kind: "flow-in", optional: true },
      { id: "loopBody", label: "循环体", kind: "flow-out" },
      { id: "loopComplete", label: "循环完成", kind: "flow-out" },
      {
        id: "startIndex",
        label: "循环起始值",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "endIndex",
        label: "循环终止值",
        kind: "data-in",
        valueType: "int",
      },
      {
        id: "currentIndex",
        label: "当前循环值",
        kind: "data-out",
        valueType: "int",
      },
    ],
  },

  // ───────────────────────────── 03-自定义仇恨 ─────────────────────────────
  // 执行节点/自定义仇恨
  {
    id: "client.action.hate.modifyByRatio",
    displayName: "按比例修改指定实体的仇恨值",
    displayNameEN: "Modify the Aggro Value of the Specified Entity Proportionally",
    officialID: 0,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "target", label: "目标实体", kind: "data-in", valueType: "entity" },
      {
        id: "owner",
        label: "仇恨拥有者实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "ratio",
        label: "修改的仇恨值比例",
        kind: "data-in",
        valueType: "float",
      },
    ],
  },
  {
    id: "client.action.hate.transferByRatio",
    displayName: "按比例转移指定实体的仇恨值",
    displayNameEN: "Transfer the Aggro Value of the Specified Entity Proportionally",
    officialID: 0,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "target",
        label: "转移目标实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "source",
        label: "转移来源实体",
        kind: "data-in",
        valueType: "entity",
      },
      {
        id: "owner",
        label: "仇恨拥有者实体",
        kind: "data-in",
        valueType: "entity",
      },
      { id: "ratio", label: "转移比例", kind: "data-in", valueType: "float" },
    ],
  },
  {
    id: "client.action.hate.taunt",
    displayName: "嘲讽目标",
    displayNameEN: "Taunt Target",
    officialID: 0,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      {
        id: "taunter",
        label: "嘲讽者实体",
        kind: "data-in",
        valueType: "entity",
      },
      { id: "target", label: "目标实体", kind: "data-in", valueType: "entity" },
    ],
  },
  {
    id: "client.action.hate.removeTargetFromList",
    displayName: "将目标实体移除出仇恨列表",
    displayNameEN: "Remove Target Entity From Aggro List",
    officialID: 0,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "target", label: "目标实体", kind: "data-in", valueType: "entity" },
      {
        id: "owner",
        label: "仇恨拥有者实体",
        kind: "data-in",
        valueType: "entity",
      },
    ],
  },
  {
    id: "client.action.hate.clearTargetList",
    displayName: "清空指定实体的仇恨列表",
    displayNameEN: "Clear the Aggro List of the Specified Entity",
    officialID: 0,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "target", label: "目标实体", kind: "data-in", valueType: "entity" },
    ],
  },
  {
    id: "client.action.hate.setValue",
    displayName: "设置指定实体的仇恨值",
    displayNameEN: "Set the Aggro Value of the Specified Entity",
    officialID: 0,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "target", label: "目标实体", kind: "data-in", valueType: "entity" },
      {
        id: "owner",
        label: "仇恨拥有者实体",
        kind: "data-in",
        valueType: "entity",
      },
      { id: "value", label: "仇恨值", kind: "data-in", valueType: "int" },
    ],
  },
  {
    id: "client.action.hate.addValue",
    displayName: "修改指定实体的仇恨值",
    displayNameEN: "Modify the Aggro Value of the Specified Entity",
    officialID: 200084,
    category: "执行节点/自定义仇恨",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },
      { id: "target", label: "目标实体", kind: "data-in", valueType: "entity" },
      {
        id: "owner",
        label: "仇恨拥有者实体",
        kind: "data-in",
        valueType: "entity",
      },
      { id: "delta", label: "仇恨值增量", kind: "data-in", valueType: "int" },
    ],
  },
  // ───────────────────────────── 04-信号 ─────────────────────────────
  // 执行节点/信号
  {
    id: "client.action.sendSignalToServer",
    displayName: "向服务器节点图发送信号",
    displayNameEN: "Send Signal to Server Node Graph",
    officialID: 0,
    category: "执行节点/信号",
    kind: "action",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      { id: "flowOut", label: "完成", kind: "flow-out" },

      {
        id: "signalName",
        label: "信号名",
        kind: "data-in",
        valueType: "string",
        ui: { placeholder: "输入字符串" },
      },
    ],
  },
  // 流程控制节点
  // ───────────────────────────── 00-通用 ─────────────────────────────
  // 流程控制节点/通用
  {
    id: "client.flow.branch.ifElse",
    displayName: "双分支",
    displayNameEN: "Double Branch",
    officialID: 0,
    category: "流程控制节点/通用",
    kind: "flow-control",
    ports: [
      { id: "flowIn", label: "执行", kind: "flow-in" },
      {
        id: "condition",
        label: "条件",
        kind: "data-in",
        valueType: "bool",
        defaultValue: false,
      },
      { id: "true", label: "是", kind: "flow-out" },
      { id: "false", label: "否", kind: "flow-out" },
    ],
  },
];