/** Types declaration for protobuf
 * This file is auto generated by utils/protobuf/proto2ts.ts
 * Do not edit this file directly.
 *
 * @version 1.1.2
 * @date Mon Nov 24 2025 15:48:47 GMT+0800 (中国标准时间)
 * @author Aluria
 * 
 * @source D:\Program\GenshinImpact\projs\Convertor\utils\protobuf/gia.proto
 * @dest D:\Program\GenshinImpact\projs\Convertor\utils\protobuf/gia.proto.ts
 * @program file:///D:/Program/GenshinImpact/projs/Convertor/utils/protobuf/proto2ts.ts
 */

export interface Root {
  /** Index = 1 */
  graph: NodeUnit;
  /** Index = 2 */
  utils: NodeUnit[];
  /** Index = 3 */
  filePath: string;
}
export interface NodeUnit {
  /** Index = 1 */
  id: NodeUnit_Id;
  /** Index = 2 */
  relatedIds: NodeUnit_Id[];
  /** Index = 3 */
  name: string;
  /** Index = 5 */
  type: NodeUnit_Type;
  /** Index = 13
   *
   * One of the field: graphType
   */
  graph?: NodeGraphWrapper;
  /** Index = 14
   *
   * One of the field: graphType
   */
  compositeDef?: CompositeDefWrapper;
  /** Index = 22
   *
   * One of the field: graphType
   */
  structureDef?: StructureDefWrapper;
}
export interface NodeUnit_Id {
  /** Index = 2 */
  type: NodeUnit_Id_Type;
  /** Index = 3 */
  kind?: NodeUnit_Id_NodeType;
  /** Index = 4 */
  id: number;
}
export const NodeUnit_Id_Type = {
  Unknown1: 0,
  Node: 1,
  Basic: 5,
  AffiliatedNode: 23,
} as const;
export type NodeUnit_Id_Type = (typeof NodeUnit_Id_Type)[keyof typeof NodeUnit_Id_Type];
export const NodeUnit_Id_NodeType = {
  Unknown2: 0,
  ClientGraph: 3,
  StructureDefinition: 15,
} as const;
export type NodeUnit_Id_NodeType = (typeof NodeUnit_Id_NodeType)[keyof typeof NodeUnit_Id_NodeType];
export const NodeUnit_Type = {
  Unknown: 0,
  EntityNode: 9,
  BooleanFilter: 10,
  Skills: 11,
  CompositeGraph: 12,
  StatusNode: 22,
  ClassNode: 23,
  StructureDefinition: 29,
  ItemNode: 46,
  IntegerFilter: 47,
} as const;
export type NodeUnit_Type = (typeof NodeUnit_Type)[keyof typeof NodeUnit_Type];
export interface NodeGraphWrapper {
  /** Index = 1 */
  inner: NodeGraphWrapper_InnerWrapper;
}
export interface NodeGraphWrapper_InnerWrapper {
  /** Index = 1 */
  graph: NodeGraph;
}
export interface CompositeDefWrapper {
  /** Index = 1 */
  inner: CompositeDefWrapper_InnerWrapper;
}
export interface CompositeDefWrapper_InnerWrapper {
  /** Index = 1 */
  def: CompositeDef;
}
export interface CompositeDef {
  /** Index = 4 */
  id: CompositeDef_Id;
  /** Index = 100 */
  inflows: CompositeDef_ControlFlow[];
  /** Index = 101 */
  outflows: CompositeDef_ControlFlow[];
  /** Index = 102 */
  inputs: CompositeDef_ParameterFlow[];
  /** Index = 103 */
  outputs: CompositeDef_ParameterFlow[];
  /** Index = 107 */
  type: CompositeDef_Type;
  /** Index = 200 */
  name: string;
  /** Index = 201 */
  description: string;
}
export interface CompositeDef_Id {
  /** Index = 1 */
  genericId: NodeGraph_Id;
  /** Index = 2 */
  concreteId: NodeGraph_Id;
  /** Index = 4 */
  graphId: NodeGraph_Id;
}
export interface CompositeDef_ParameterFlow {
  /** Index = 1 */
  name: string;
  /** Index = 2 */
  visible: boolean;
  /** Index = 3 */
  index: NodePin_Index;
  /** Index = 4 */
  type: CompositeDef_ParameterFlow_Type;
  /** Index = 8 */
  pinIndex: number;
}
export interface CompositeDef_ParameterFlow_Type {
  /** Index = 1 */
  class: VarBase_Class;
  /** Index = 3 */
  type1: VarType;
  /** Index = 4 */
  type2: VarType;
  /** Index = 105
   *
   * One of the field: type
   */
  mapType?: CompositeDef_ParameterFlow_Type_MapType;
  /** Index = 104 */
  valueId: CompositeDef_ParameterFlow_Type_ID;
}
export interface CompositeDef_ParameterFlow_Type_MapType {
  /** Index = 3 */
  key: VarType;
  /** Index = 4 */
  value: VarType;
}
export interface CompositeDef_ParameterFlow_Type_ID {
  /** Index = 2 */
  id: number;
}
export interface CompositeDef_ControlFlow {
  /** Index = 1 */
  name: string;
  /** Index = 2 */
  visible: boolean;
  /** Index = 3 */
  index: NodePin_Index;
  /** Index = 4 */
  description: string;
  /** Index = 8 */
  pinIndex: number;
}
export interface CompositeDef_Type {
  /** Index = 1 */
  kind: CompositeDef_Type_Kind;
  /** Index = 104
   *
   * One of the field: parent
   */
  assemble?: CompositeDef_Type_Id;
  /** Index = 105
   *
   * One of the field: parent
   */
  split?: CompositeDef_Type_Id;
  /** Index = 106
   *
   * One of the field: parent
   */
  modify?: CompositeDef_Type_Id;
}
export const CompositeDef_Type_Kind = {
  Unknown: 0,
  Composite: 1000,
  Assemble: 1003,
  Split: 1004,
  Modify: 1005,
} as const;
export type CompositeDef_Type_Kind = (typeof CompositeDef_Type_Kind)[keyof typeof CompositeDef_Type_Kind];
export interface CompositeDef_Type_Id {
  /** Index = 1 */
  id: number;
}
export interface NodeGraph {
  /** Index = 1 */
  id: NodeGraph_Id;
  /** Index = 2 */
  name: string;
  /** Index = 3 */
  nodes: GraphNode[];
  /** Index = 4 */
  compositePins: CompositePin[];
  /** Index = 6 */
  graphValues: GraphVariable[];
  /** Index = 7 */
  affiliations: GraphAffiliation[];
}
export interface NodeGraph_Id {
  /** Index = 1 */
  class: NodeGraph_Id_Class;
  /** Index = 2 */
  type: NodeGraph_Id_Type;
  /** Index = 3 */
  kind: NodeGraph_Id_Kind;
  /** Index = 5 */
  id: number;
}
export const NodeGraph_Id_Class = {
  Unknown1: 0,
  UserDefined: 10000,
  SystemDefined: 10001,
} as const;
export type NodeGraph_Id_Class = (typeof NodeGraph_Id_Class)[keyof typeof NodeGraph_Id_Class];
export const NodeGraph_Id_Type = {
  Unknown2: 0,
  BasicNode: 20000,
  BooleanFilter: 20001,
  Skills: 20002,
  StatusNode: 20003,
  ClassNode: 20004,
  ItemNode: 20005,
  IntegerFilter: 20006,
} as const;
export type NodeGraph_Id_Type = (typeof NodeGraph_Id_Type)[keyof typeof NodeGraph_Id_Type];
export const NodeGraph_Id_Kind = {
  Unknown3: 0,
  NodeGraph: 21001,
  CompositeGraph: 21002,
  SysCall: 22000,
  SysGraph: 22001,
} as const;
export type NodeGraph_Id_Kind = (typeof NodeGraph_Id_Kind)[keyof typeof NodeGraph_Id_Kind];
export interface GraphAffiliation {
  /** Index = 1 */
  info: GraphAffiliation_Info;
  /** Index = 2 */
  type: GraphAffiliation_Type;
}
export interface GraphAffiliation_Info {
  /** Index = 1 */
  source: NodeGraph_Id;
  /** Index = 2 */
  typeXxx: number;
  /** Index = 3 */
  alwaysOneXxxx: number;
  /** Index = 100
   *
   * One of the field: extend
   */
  structId?: VarBase_ItemType_StructItem;
}
export interface GraphAffiliation_Type {
  /** Index = 1 */
  type: number;
}
export interface StructureDefWrapper {
  /** Index = 1 */
  def: StructureDefWrapper_StructureDef;
}
export interface StructureDefWrapper_StructureDef {
  /** Index = 1 */
  genericField: StructureDefWrapper_Field;
  /** Index = 2 */
  connectField: StructureDefWrapper_Field;
  /** Index = 3 */
  index: number;
  /** Index = 4 */
  itemCount: number;
}
export interface StructureDefWrapper_Field {
  /** Index = 1 */
  id: number;
  /** Index = 3 */
  vars: StructureDefWrapper_VarDef[];
  /** Index = 501 */
  structName: string;
  /** Index = 502 */
  classBase: number;
  /** Index = 503 */
  index: number;
}
export interface StructureDefWrapper_VarDef {
  /** Index = 1 */
  id: StructureDefWrapper_VarDef_Id;
  /** Index = 3 */
  def: StructureDefWrapper_VarDef_Content;
  /** Index = 5 */
  name: string;
  /** Index = 501 */
  name2: string;
  /** Index = 502 */
  type: VarType;
  /** Index = 503 */
  index: number;
}
export interface StructureDefWrapper_VarDef_SubType {
  /** Index = 1 */
  xxx: number;
  /** Index = 2 */
  xxxx: number;
  /** Index = 502 */
  key: VarType;
  /** Index = 503 */
  value: VarType;
  /** Index = 504 */
  valueId: number;
}
export interface StructureDefWrapper_VarDef_Id {
  /** Index = 1 */
  type: VarType;
  /** Index = 2 */
  sub: StructureDefWrapper_VarDef_SubType;
}
export interface StructureDefWrapper_VarDef_Content {
  /** Index = 1 */
  type: VarType;
  /** Index = 2 */
  sub: StructureDefWrapper_VarDef_SubType;
  /** Index = 13
   *
   * One of the field: val
   */
  intVal?: IntBaseValue;
  /** Index = 14
   *
   * One of the field: val
   */
  boolVal?: EnumBaseValue;
  /** Index = 16
   *
   * One of the field: val
   */
  strVal?: StringBaseValue;
}
export const VarType = {
  UnknownVar: 0,
  Entity: 1,
  GUID: 2,
  Integer: 3,
  Boolean: 4,
  Float: 5,
  String: 6,
  GUIDList: 7,
  IntegerList: 8,
  BooleanList: 9,
  FloatList: 10,
  StringList: 11,
  Vector: 12,
  EntityList: 13,
  EnumItem: 14,
  VectorList: 15,
  Faction: 17,
  Configuration: 20,
  Prefab: 21,
  ConfigurationList: 22,
  PrefabList: 23,
  FactionList: 24,
  Struct: 25,
  StructList: 26,
  Dictionary: 27,
} as const;
export type VarType = (typeof VarType)[keyof typeof VarType];
export interface GraphVariable {
  /** Index = 2 */
  name: string;
  /** Index = 3 */
  type: VarType;
  /** Index = 4 */
  values: VarBase;
  /** Index = 5 */
  exposed: boolean;
  /** Index = 6 */
  structId: number;
  /** Index = 7 */
  keyType: VarType;
  /** Index = 8 */
  valueType: VarType;
}
export interface VarBase {
  /** Index = 1 */
  class: VarBase_Class;
  /** Index = 2 */
  alreadySetVal: boolean;
  /** Index = 4 */
  itemType?: VarBase_ItemType;
  /** Index = 5 */
  structInfo?: VarBase_StructInfo;
  /** Index = 101
   *
   * One of the field: baseValues
   */
  bId?: IdBaseValue;
  /** Index = 102
   *
   * One of the field: baseValues
   */
  bInt?: IntBaseValue;
  /** Index = 104
   *
   * One of the field: baseValues
   */
  bFloat?: FloatBaseValue;
  /** Index = 105
   *
   * One of the field: baseValues
   */
  bString?: StringBaseValue;
  /** Index = 106
   *
   * One of the field: baseValues
   */
  bEnum?: EnumBaseValue;
  /** Index = 107
   *
   * One of the field: baseValues
   */
  bVector?: VectorBaseValue;
  /** Index = 108
   *
   * One of the field: baseValues
   */
  bStruct?: StructBaseValue;
  /** Index = 109
   *
   * One of the field: baseValues
   */
  bArray?: ArrayBaseValue;
  /** Index = 110
   *
   * One of the field: baseValues
   */
  bNodeValue?: NodeValueBaseValue;
  /** Index = 111
   *
   * One of the field: baseValues
   */
  bMapPair?: MapPairBaseValue;
  /** Index = 112
   *
   * One of the field: baseValues
   */
  bMap?: MapBaseValue;
}
export const VarBase_Class = {
  Unknown: 0,
  IdBase: 1,
  IntBase: 2,
  FloatBase: 4,
  StringBase: 5,
  EnumBase: 6,
  VectorBase: 7,
  NodeValueBase: 10000,
  StructBase: 10001,
  ArrayBase: 10002,
  MapBase: 10003,
  MapPair: 10007,
} as const;
export type VarBase_Class = (typeof VarBase_Class)[keyof typeof VarBase_Class];
export interface VarBase_ItemType {
  /** Index = 1 */
  classBase: number;
  /** Index = 100 */
  itemType: VarBase_ItemType_Inner;
}
export interface VarBase_ItemType_StructItem {
  /** Index = 1 */
  structId: number;
}
export interface VarBase_ItemType_Inner {
  /** Index = 1 */
  type: VarType;
  /** Index = 2 */
  kind: VarBase_ItemType_Inner_Kind;
  /** Index = 100
   *
   * One of the field: id
   */
  item?: VarBase_ItemType_StructItem;
  /** Index = 101
   *
   * One of the field: id
   */
  items?: VarBase_ItemType_Inner_PairItems;
}
export const VarBase_ItemType_Inner_Kind = {
  Normal: 0,
  Struct: 1,
  Pair: 2,
} as const;
export type VarBase_ItemType_Inner_Kind = (typeof VarBase_ItemType_Inner_Kind)[keyof typeof VarBase_ItemType_Inner_Kind];
export interface VarBase_ItemType_Inner_PairItems {
  /** Index = 1 */
  key: VarType;
  /** Index = 2 */
  value: VarType;
  /** Index = 3 */
  structId: number;
}
export interface VarBase_StructInfo {
  /** Index = 1 */
  xxx: number;
  /** Index = 100 */
  inner: VarBase_StructInfo_Inner;
}
export interface VarBase_StructInfo_Inner {
  /** Index = 1 */
  xxx: number;
}
export interface IdBaseValue {
  /** Index = 1 */
  val: number;
}
export interface IntBaseValue {
  /** Index = 1 */
  val: number;
}
export interface FloatBaseValue {
  /** Index = 1 */
  val: number;
}
export interface StringBaseValue {
  /** Index = 1 */
  val: string;
}
export interface EnumBaseValue {
  /** Index = 1 */
  val: EnumNode_Value;
}
export interface VectorBaseValue {
  /** Index = 1 */
  val: VectorBaseValue_Vec;
}
export interface VectorBaseValue_Vec {
  /** Index = 1 */
  x: number;
  /** Index = 2 */
  y: number;
  /** Index = 3 */
  z: number;
}
export interface StructBaseValue {
  /** Index = 1 */
  items: VarBase[];
}
export interface ArrayBaseValue {
  /** Index = 1 */
  entries: VarBase[];
}
export interface MapBaseValue {
  /** Index = 1 */
  mapPairs: VarBase[];
}
export interface MapPairBaseValue {
  /** Index = 1 */
  key: VarBase;
  /** Index = 2 */
  value: VarBase;
}
export interface NodeValueBaseValue {
  /** Index = 1 */
  indexOfConcrete: number;
  /** Index = 2 */
  value: VarBase;
  /** Index = 5 */
  wrapper?: NodeValueBaseValue_Wrapper;
}
export interface NodeValueBaseValue_Wrapper {
  /** Index = 4 */
  classBase: number;
  /** Index = 100 */
  inner: NodeValueBaseValue_Wrapper_Inner;
}
export interface NodeValueBaseValue_Wrapper_Inner {
  /** Index = 1 */
  wrapper: NodeValueBaseValue_Wrapper_Inner_Wrapper;
}
export interface NodeValueBaseValue_Wrapper_Inner_Wrapper {
  /** Index = 1 */
  class: VarBase_Class;
  /** Index = 100
   *
   * One of the field: type
   */
  item?: VarBase_ItemType_StructItem;
}
export interface GraphNode {
  /** Index = 1 */
  nodeIndex: number;
  /** Index = 2 */
  genericId: NodeProperty;
  /** Index = 3 */
  concreteId: NodeProperty;
  /** Index = 4 */
  pins: NodePin[];
  /** Index = 5 */
  x: number;
  /** Index = 6 */
  y: number;
  /** Index = 10 */
  usingStruct: GraphAffiliation_Info[];
}
export interface NodeProperty {
  /** Index = 1 */
  class: NodeGraph_Id_Class;
  /** Index = 2 */
  type: NodeProperty_Type;
  /** Index = 3 */
  kind: NodeGraph_Id_Kind;
  /** Index = 5 */
  nodeId: NodeId;
}
export const NodeProperty_Type = {
  Unknown: 0,
  Server: 20000,
  Client: 20002,
} as const;
export type NodeProperty_Type = (typeof NodeProperty_Type)[keyof typeof NodeProperty_Type];
export interface NodePin {
  /** Index = 1 */
  i1: NodePin_Index;
  /** Index = 2 */
  i2: NodePin_Index;
  /** Index = 3 */
  value: VarBase;
  /** Index = 4 */
  type: VarType;
  /** Index = 5 */
  connects: NodeConnection[];
}
export interface NodePin_Index {
  /** Index = 1 */
  kind: NodePin_Index_Kind;
  /** Index = 2 */
  index: number;
}
export const NodePin_Index_Kind = {
  Unknown: 0,
  InFlow: 1,
  OutFlow: 2,
  InParam: 3,
  OutParam: 4,
} as const;
export type NodePin_Index_Kind = (typeof NodePin_Index_Kind)[keyof typeof NodePin_Index_Kind];
export interface NodeConnection {
  /** Index = 1 */
  id: number;
  /** Index = 2 */
  connect: NodePin_Index;
  /** Index = 3 */
  connect2: NodePin_Index;
}
export interface CompositePin {
  /** Index = 1 */
  outerPin: NodePin_Index;
  /** Index = 2 */
  innerNodeId: number;
  /** Index = 3 */
  innerPin: NodePin_Index;
  /** Index = 4 */
  innerPin2: NodePin_Index;
}
export const NodeId = {
  Unknown: 0,
  EnumEqual_Generic: 475,
  EnumEqual_Comparison_Operators: 476,
  EnumEqual_Logical_Operators: 477,
  EnumEqual_Mathematical_Operators: 478,
  EnumEqual_Attack_Shapes: 479,
  EnumEqual_Survival_Status: 480,
  EnumEqual_Sorting_Rules: 481,
  EnumEqual_Rounding_Logic: 482,
  EnumEqual_Type_Conversions: 483,
  EnumEqual_Motion_Path_Point_Types: 484,
  EnumEqual_Motion_Types: 485,
  EnumEqual_Follow_Location_Type: 486,
  EnumEqual_Coordinate_System_Type: 487,
  EnumEqual_Elemental_Type: 488,
  EnumEqual_Entity_Type: 489,
  EnumEqual_Unit_Status_Addition_Result: 491,
  EnumEqual_Unit_Status_Removal_Reason: 492,
  EnumEqual_Unit_Status_Removal_Strategy: 493,
  EnumEqual_Revive_Point_Selection_Strategy: 494,
  EnumEqual_Cause_Of_Being_Down: 495,
  EnumEqual_Trigonometric_Functions: 496,
  EnumEqual_Disruptor_Device_Types: 497,
  EnumEqual_Disruptor_Device_Orientation: 498,
  EnumEqual_UI_Control_Group_Status: 499,
  EnumEqual_Target_Type: 500,
  EnumEqual_Trigger_Restriction: 501,
  EnumEqual_Hit_Type: 502,
  EnumEqual_Attack_Type: 503,
  EnumEqual_Hit_Performance_Level: 504,
  EnumEqual_Skill_Slot: 3351,
  EnumEqual_Sound_Attenuation_Mode: 3352,
  EnumEqual_Select_Completion_Reason: 3353,
  EnumEqual_Settlement_Status: 3354,
  EnumEqual_Reason_For_Item_Change: 3356,
  EnumEqual_Item_Loot_Type: 3357,
  EnumEqual_Decision_Refresh_Mode: 3358,
  EnumEqual_Elemental_Reaction_Type: 3359,
  EnumEqual_Interrupt_Status: 759,
  EnumEqual_Gameplay_Mode: 776,
  EnumEqual_Input_Device_Type: 777,
} as const;
export type NodeId = (typeof NodeId)[keyof typeof NodeId];
export interface EnumNode {
}
export const EnumNode_EnumEqualList = {
  Generic: 0,
  Comparison_Operators: 1,
  Logical_Operators: 2,
  Mathematical_Operators: 3,
  Attack_Shapes: 4,
  Survival_Status: 5,
  Sorting_Rules: 6,
  Rounding_Logic: 7,
  Type_Conversions: 8,
  Motion_Path_Point_Types: 9,
  Motion_Types: 10,
  Follow_Location_Type: 11,
  Coordinate_System_Type: 12,
  Elemental_Type: 13,
  Entity_Type: 14,
  Unit_Status_Addition_Result: 16,
  Unit_Status_Removal_Reason: 17,
  Unit_Status_Removal_Strategy: 18,
  Revive_Point_Selection_Strategy: 19,
  Cause_Of_Being_Down: 20,
  Trigonometric_Functions: 21,
  Disruptor_Device_Types: 22,
  Disruptor_Device_Orientation: 23,
  UI_Control_Group_Status: 24,
  Target_Type: 25,
  Trigger_Restriction: 26,
  Hit_Type: 27,
  Attack_Type: 28,
  Hit_Performance_Level: 29,
  Skill_Slot: 30,
  Sound_Attenuation_Mode: 31,
  Select_Completion_Reason: 32,
  Settlement_Status: 33,
  Reason_For_Item_Change: 35,
  Item_Loot_Type: 36,
  Decision_Refresh_Mode: 37,
  Elemental_Reaction_Type: 38,
  Interrupt_Status: 39,
  Gameplay_Mode: 40,
  Input_Device_Type: 41,
} as const;
export type EnumNode_EnumEqualList = (typeof EnumNode_EnumEqualList)[keyof typeof EnumNode_EnumEqualList];
export const EnumNode_Value = {
  Default: 0,
  ComparisonOperators_EqualTo: 100,
  ComparisonOperators_LessThan: 101,
  ComparisonOperators_LessThanOrEqualTo: 102,
  ComparisonOperators_GreaterThan: 103,
  ComparisonOperators_GreaterThanOrEqualTo: 104,
  LogicalOperators_AND: 200,
  LogicalOperators_OR: 201,
  LogicalOperators_XOR: 202,
  LogicalOperators_NOT: 203,
  MathematicalOperators_Addition: 300,
  MathematicalOperators_Subtraction: 301,
  MathematicalOperators_Multiplication: 302,
  MathematicalOperators_Division: 303,
  MathematicalOperators_ModuloOperation: 304,
  MathematicalOperators_Exponentiation: 305,
  MathematicalOperators_GetMaximumValue: 306,
  MathematicalOperators_GetMinimumValue: 307,
  MathematicalOperators_Logarithm: 308,
  AttackShapes_Rectangle: 400,
  AttackShapes_Sphere: 401,
  AttackShapes_Sector: 402,
  SurvivalStatus_Alive: 500,
  SurvivalStatus_Down: 501,
  SortingRules_Ascending: 600,
  SortingRules_Descending: 601,
  RoundingLogic_RoundUp: 700,
  RoundingLogic_RoundDown: 701,
  RoundingLogic_RoundToNearest: 702,
  RoundingLogic_Truncate: 703,
  TypeConversions_IntegerToBoolean: 800,
  TypeConversions_IntegerToFloatingPoint: 801,
  TypeConversions_IntegerToString: 802,
  TypeConversions_EntityToString: 803,
  TypeConversions_GUIDToString: 804,
  TypeConversions_BooleanToInteger: 805,
  TypeConversions_BooleanToString: 806,
  TypeConversions_FloatingPointToInteger: 807,
  TypeConversions_FloatingPointToString: 808,
  TypeConversions_3DVectorToString: 809,
  TypeConversions_FactionToString: 810,
  MotionPathPointTypes_StraightLine: 900,
  MotionPathPointTypes_Curve: 901,
  MotionTypes_OneWay: 1000,
  MotionTypes_BackAndForth: 1001,
  MotionTypes_CyclicMovement: 1002,
  FollowLocationType_CompletelyFollow: 1100,
  FollowLocationType_FollowLocation: 1101,
  FollowLocationType_FollowRotation: 1102,
  CoordinateSystemType_RelativeCoordinateSystem: 1200,
  CoordinateSystemType_WorldCoordinateSystem: 1201,
  ElementalType_None: 1300,
  ElementalType_Pyro: 1301,
  ElementalType_Hydro: 1302,
  ElementalType_Anemo: 1303,
  ElementalType_Electro: 1304,
  ElementalType_Dendro: 1305,
  ElementalType_Cryo: 1306,
  ElementalType_Geo: 1307,
  EntityType_Stage: 1401,
  EntityType_Object: 1402,
  EntityType_Player: 1403,
  EntityType_Character: 1404,
  EntityType_Creation: 1405,
  UnitStatusAdditionResult_FailedUnexpectedError: 1500,
  UnitStatusAdditionResult_FailedOperationPausedForAnotherProcess: 1501,
  UnitStatusAdditionResult_FailedMaximumCoexistenceLimitReached: 1502,
  UnitStatusAdditionResult_FailedUnableToAddAdditionalStack: 1503,
  UnitStatusAdditionResult_SuccessNewStatusApplied: 1504,
  UnitStatusAdditionResult_SuccessSlotStacking: 1505,
  UnitStatusRemovalReason_ReplacedByOtherUnitStatus: 1506,
  UnitStatusRemovalReason_DurationExceeded: 1507,
  UnitStatusRemovalReason_Dispelled: 1508,
  UnitStatusRemovalReason_StatusExpired: 1509,
  UnitStatusRemovalReason_ClassChanged: 1510,
  UnitStatusRemovalStrategy_AllCoexistingStatusesWithTheSameName: 1540,
  UnitStatusRemovalStrategy_StatusWithFastestStackLoss: 1541,
  RevivePointSelectionStrategy_Nearest: 1601,
  RevivePointSelectionStrategy_MostRecentlyActivated: 1602,
  RevivePointSelectionStrategy_HighestPriority: 1603,
  RevivePointSelectionStrategy_Random: 1604,
  CauseOfBeingDown_NodeGraphTriggered: 1605,
  CauseOfBeingDown_NormalDefeat: 1606,
  CauseOfBeingDown_AbnormalDefeat: 1607,
  TrigonometricFunctions_cos: 1700,
  TrigonometricFunctions_sin: 1701,
  TrigonometricFunctions_tan: 1702,
  TrigonometricFunctions_arccos: 1703,
  TrigonometricFunctions_arcsin: 1704,
  TrigonometricFunctions_arctan: 1705,
  TrigonometricFunctions_RadiansToDegrees: 1706,
  TrigonometricFunctions_DegreesToRadians: 1707,
  DisruptorDeviceTypes_ForceFieldDevice: 1801,
  DisruptorDeviceTypes_Ejector: 1802,
  DisruptorDeviceTypes_TractorDevice: 1803,
  DisruptorDeviceOrientation_AssociateCharacterOrientation: 1810,
  DisruptorDeviceOrientation_FixedUnidirectional: 1811,
  UIControlGroupStatus_Off: 1900,
  UIControlGroupStatus_On: 1901,
  UIControlGroupStatus_Hidden: 1902,
  TargetType_None: 2000,
  TargetType_AlliedFaction: 2001,
  TargetType_HostileFaction: 2002,
  TargetType_Self: 2003,
  TargetType_OwnFaction: 2004,
  TargetType_All: 2005,
  TargetType_AllExceptSelf: 2006,
  TargetType_AlliedFactionSelfIncluded: 2007,
  TriggerRestriction_TriggerOnlyOnce: 2101,
  TriggerRestriction_TriggerOnlyOncePerEntity: 2102,
  HitType_None: 2200,
  HitType_Default: 2201,
  HitType_Slash: 2202,
  HitType_Smash: 2203,
  HitType_Projectile: 2204,
  HitType_PiercingAttack: 2205,
  AttackType_None: 2300,
  AttackType_MeleeAttack: 2301,
  AttackType_RangedAttack: 2302,
  AttackType_Default: 2303,
  HitPerformanceLevel_Default: 2400,
  HitPerformanceLevel_NoHitPerformance: 2401,
  HitPerformanceLevel_HitByNormalArrowWithoutCharging: 2402,
  HitPerformanceLevel_ComboHit: 2403,
  HitPerformanceLevel_NormalHit: 2404,
  HitPerformanceLevel_HeavyHit: 2405,
  HitPerformanceLevel_StrongImpact: 2406,
  HitPerformanceLevel_UltimateImpact: 2407,
  HitPerformanceLevel_VerticalLaunch: 2408,
  HitPerformanceLevel_SuperLaunch: 2409,
  HitPerformanceLevel_LongRangeThrow: 2410,
  SkillSlot_NormalAttack: 3100,
  SkillSlot_1E: 3111,
  SkillSlot_2Q: 3112,
  SkillSlot_3R: 3113,
  SkillSlot_4T: 3114,
  SkillSlot_CustomSkillSlot1: 3121,
  SkillSlot_CustomSkillSlot2: 3122,
  SkillSlot_CustomSkillSlot3: 3123,
  SkillSlot_CustomSkillSlot4: 3124,
  SkillSlot_CustomSkillSlot5: 3125,
  SkillSlot_CustomSkillSlot6: 3126,
  SkillSlot_CustomSkillSlot7: 3127,
  SkillSlot_CustomSkillSlot8: 3128,
  SkillSlot_CustomSkillSlot9: 3129,
  SkillSlot_CustomSkillSlot10: 3130,
  SkillSlot_CustomSkillSlot11: 3131,
  SkillSlot_CustomSkillSlot12: 3132,
  SkillSlot_CustomSkillSlot13: 3133,
  SkillSlot_CustomSkillSlot14: 3134,
  SkillSlot_CustomSkillSlot15: 3135,
  SoundAttenuationMode_LinearAttenuation: 3400,
  SoundAttenuationMode_FastThenSlow: 3401,
  SoundAttenuationMode_SlowThenFast: 3402,
  SelectCompletionReason_CompletedByPlayer: 3500,
  SelectCompletionReason_Timeout: 3501,
  SelectCompletionReason_FixedQuantityRefresh: 3502,
  SelectCompletionReason_RefreshAll: 3503,
  SelectCompletionReason_ClosedManually: 3504,
  SelectCompletionReason_ClosedByNodeGraph: 3505,
  SettlementStatus_TBC: 4100,
  SettlementStatus_Victory: 4101,
  SettlementStatus_Failed: 4102,
  ReasonForItemChange_Destroy: 4900,
  ReasonForItemChange_Discard: 4901,
  ReasonForItemChange_Use: 4902,
  ReasonForItemChange_DefeatDrops: 4903,
  ReasonForItemChange_ShopTrade: 4904,
  ReasonForItemChange_NodeGraphOperation: 4905,
  ReasonForItemChange_PickUp: 4950,
  ItemLootType_SharedReward: 4350,
  ItemLootType_IndividualizedReward: 4351,
  DecisionRefreshMode_CannotRefresh: 3510,
  DecisionRefreshMode_PartialRefresh: 3511,
  DecisionRefreshMode_RefreshAll: 3512,
  ElementalReactionType_Overloaded: 4701,
  ElementalReactionType_Vaporize: 4702,
  ElementalReactionType_Burning: 4703,
  ElementalReactionType_Wet: 4705,
  ElementalReactionType_Bloom: 4706,
  ElementalReactionType_Melt: 4707,
  ElementalReactionType_Frozen: 4708,
  ElementalReactionType_ElectroCharged: 4712,
  ElementalReactionType_Superconduct: 4716,
  ElementalReactionType_SwirlPyro: 4717,
  ElementalReactionType_SwirlHydro: 4718,
  ElementalReactionType_SwirlElectro: 4719,
  ElementalReactionType_SwirlCryo: 4720,
  ElementalReactionType_CrystallizePyro: 4727,
  ElementalReactionType_CrystallizeHydro: 4728,
  ElementalReactionType_CrystallizeElectro: 4729,
  ElementalReactionType_CrystallizeCryo: 4730,
  ElementalReactionType_Catalyze: 4733,
  ElementalReactionType_Aggravate: 4734,
  ElementalReactionType_Spread: 4735,
  ElementalReactionType_Burgeon: 4736,
  ElementalReactionType_Hyperbloom: 4737,
  InterruptStatus_InterruptResistanceStatus: 5200,
  InterruptStatus_InterruptVulnerabilityStatus: 5201,
  InterruptStatus_ProtectedStatus: 5202,
  GameplayMode_Play: 5700,
  GameplayMode_RoomPlay: 5701,
  GameplayMode_MatchPlay: 5702,
  InputDeviceType_KeyboardAndMouse: 5800,
  InputDeviceType_Controller: 5801,
  InputDeviceType_Touchscreen: 5802,
} as const;
export type EnumNode_Value = (typeof EnumNode_Value)[keyof typeof EnumNode_Value];
