/** Types declaration for protobuf
 * This file is auto generated by utils/protobuf/proto2ts.ts
 * Do not edit this file directly.
 *
 * @version 2.2.0
 * @date Wed Jan 14 2026 23:35:23 GMT+0800 (中国标准时间)
 * @author Aluria
 * @author MiemieMethod
 * 
 * @source D:\Program\GenshinImpact\projs\Convertor\utils\protobuf/gia.proto
 * @dest D:\Program\GenshinImpact\projs\Convertor\utils\protobuf/gia.proto.ts
 * @program file:///D:/Program/GenshinImpact/projs/Convertor/utils/protobuf/proto2ts.ts
 */

export interface AssetBundle {
  /** Index = 1 */
  primary_resource: ResourceEntry;
  /** Index = 2 */
  dependencies: ResourceEntry[];
  /** Index = 3 */
  export_tag: string;
  /** Index = 5 */
  engine_version: string;
}
export interface ResourceEntry {
  /** Index = 1 */
  identity: ResourceLocator;
  /** Index = 2 */
  reference_list: ResourceLocator[];
  /** Index = 3 */
  internal_name: string;
  /** Index = 5 */
  resource_class: ResourceEntry_ResourceClass;
  /** Index = 13
   *
   * One of the field: payload
   */
  graph_data?: NodeGraphContainer;
  /** Index = 14
   *
   * One of the field: payload
   */
  interface_data?: NodeInterfaceContainer;
  /** Index = 22
   *
   * One of the field: payload
   */
  struct_data?: StructureDefinitionContainer;
}
export const ResourceEntry_ResourceClass = {
  UNKNOWN_TYPE: 0,
  OBJECT: 1,
  CREATION: 2,
  OBJECT_ENTITY: 3,
  CREATION_ENTITY: 4,
  TERRAIN_ENTITY: 5,
  PRESET_POINT: 6,
  UNIT_STATUS: 7,
  SKILL: 8,
  ENTITY_NODE_GRAPH: 9,
  BOOLEAN_FILTER_GRAPH: 10,
  SKILL_NODE_GRAPH: 11,
  COMPOSITE_NODE_DECL: 12,
  CAMERA: 13,
  SIGNAL_NODE_DECL: 14,
  UI_CONTROL: 15,
  SKILL_RESOURCE: 16,
  CLASS: 17,
  PLAYER_TEMPLATE: 18,
  CHARACTER_TEMPLATE: 19,
  INTERFACE_LAYOUT: 20,
  UI_CONTROL_GROUP: 21,
  STATUS_NODE_GRAPH: 22,
  CLASS_NODE_GRAPH: 23,
  GLOBAL_TIMER: 24,
  PROJECTILE: 25,
  ITEM: 26,
  DECORATION: 28,
  STRUCTURE: 29,
  SHOP_TEMPLATE: 30,
  CURRENCY: 35,
  LEVEL_STRUCTURE: 37,
  PATH: 38,
  SHIELD: 39,
  ENTITY_DEPLOYMENT_GROUP: 43,
  UNIT_TAG: 44,
  SCAN_TAG: 45,
  ITEM_NODE_GRAPH: 46,
  INTEGER_FILTER_GRAPH: 47,
  LIGHT_SOURCE: 48,
  ENVIRONMENT_CONFIGURATION: 49,
  CREATION_DECISION_NODE_GRAPH: 51,
  CREATION_SKILL_NODE_GRAPH: 52,
  CREATION_STATUS_NODE_GRAPH: 53,
} as const;
export type ResourceEntry_ResourceClass = (typeof ResourceEntry_ResourceClass)[keyof typeof ResourceEntry_ResourceClass];
export interface ResourceLocator {
  /** Index = 1 */
  source_domain: ResourceLocator_Origin;
  /** Index = 2 */
  service_domain: ResourceLocator_Category;
  /** Index = 3 */
  kind: ResourceLocator_AssetKind;
  /** Index = 4 */
  asset_guid: number;
  /** Index = 5 */
  runtime_id: number;
}
export const ResourceLocator_Origin = {
  UNKNOWN_ORIGIN: 0,
  USER_DEFINED: 10000,
  SYSTEM_DEFINED: 10001,
} as const;
export type ResourceLocator_Origin = (typeof ResourceLocator_Origin)[keyof typeof ResourceLocator_Origin];
export const ResourceLocator_Category = {
  UNKNOWN_CATEGORY: 0,
  DEFAULT: 1,
  SERVER_NODE_GRAPH: 5,
  NODE_DECL: 23,
  GLOBAL_TIMER: 24,
  CAMERA: 25,
  SERVER_BASIC: 20000,
  SERVER_STATUS: 20003,
  SERVER_CLASS: 20004,
  SERVER_ITEM: 20005,
  CLIENT_FILTER: 20001,
  CLIENT_SKILL: 20002,
  CLIENT_INT_FILTER: 20006,
  CREATION_GRAPH: 20007,
  CREATION_SKILL: 20008,
  CREATION_STATUS: 20009,
} as const;
export type ResourceLocator_Category = (typeof ResourceLocator_Category)[keyof typeof ResourceLocator_Category];
export const ResourceLocator_AssetKind = {
  BASIC: 0,
  PREFAB: 1,
  ENTITY: 2,
  SERVER_CONFIGURATION_OR_CLIENT_NODE_GRAPH: 3,
  TERRAIN: 5,
  UI: 8,
  PRESET_POINT: 9,
  DECORATION: 14,
  STRUCTURE: 15,
  ENTITY_DEPLOYMENT_GROUP: 18,
  PATH: 19,
  UNIT_TAG: 23,
  CUSTOM_GRAPH: 21001,
  COMPOSITE_GRAPH: 21002,
  SYS_CALL_STUB: 22000,
  GENERATED_STUB: 22001,
} as const;
export type ResourceLocator_AssetKind = (typeof ResourceLocator_AssetKind)[keyof typeof ResourceLocator_AssetKind];
export const ServerTypeId = {
  SERVER_UNKNOWN: 0,
  S_ENTITY: 1,
  S_GUID: 2,
  S_INT: 3,
  S_BOOL: 4,
  S_FLOAT: 5,
  S_STRING: 6,
  S_VECTOR: 12,
  S_GUID_LIST: 7,
  S_INT_LIST: 8,
  S_BOOL_LIST: 9,
  S_FLOAT_LIST: 10,
  S_STRING_LIST: 11,
  S_ENTITY_LIST: 13,
  S_VECTOR_LIST: 15,
  S_ENUM_ITEM: 14,
  S_FACTION: 17,
  S_ENUM_LIST: 18,
  S_CONFIG: 20,
  S_PREFAB: 21,
  S_CONFIG_LIST: 22,
  S_PREFAB_LIST: 23,
  S_FACTION_LIST: 24,
  S_STRUCT: 25,
  S_STRUCT_LIST: 26,
  S_DICT: 27,
  S_LOCAL_VAR_REF: 16,
  S_VAR_SNAPSHOT_REF: 28,
} as const;
export type ServerTypeId = (typeof ServerTypeId)[keyof typeof ServerTypeId];
export const ClientTypeId = {
  CLIENT_UNKNOWN: 0,
  C_ENTITY: 1,
  C_ENTITY_LIST: 2,
  C_INT: 3,
  C_INT_LIST: 4,
  C_BOOL: 5,
  C_BOOL_LIST: 6,
  C_FLOAT: 7,
  C_FLOAT_LIST: 8,
  C_STRING: 9,
  C_STRING_LIST: 10,
  C_VECTOR: 11,
  C_VECTOR_LIST: 12,
  C_ENUM_ITEM: 13,
  C_ENUM_LIST: 17,
  C_GUID: 14,
  C_GUID_LIST: 15,
  C_FACTION: 16,
  C_FACTION_LIST: 25,
  C_CONFIG: 18,
  C_CONFIG_LIST: 20,
  C_PREFAB: 19,
  C_PREFAB_LIST: 21,
  C_STRUCT: 22,
  C_STRUCT_LIST: 23,
  C_DICT: 24,
} as const;
export type ClientTypeId = (typeof ClientTypeId)[keyof typeof ClientTypeId];
export interface TypeDefinition {
  /** Index = 1 */
  backend: TypeDefinition_Backend;
  /** Index = 100
   *
   * One of the field: type_detail
   */
  server_side?: TypeDefinition_ServerType;
  /** Index = 101
   *
   * One of the field: type_detail
   */
  client_side?: TypeDefinition_ClientType;
}
export const TypeDefinition_Backend = {
  UNKNOWN: 0,
  SERVER: 1,
  CLIENT: 2,
} as const;
export type TypeDefinition_Backend = (typeof TypeDefinition_Backend)[keyof typeof TypeDefinition_Backend];
export interface TypeDefinition_StructReference {
  /** Index = 1 */
  schema_id: number;
}
export interface TypeDefinition_MapKeyValueBinding {
  /** Index = 1 */
  key_type: number;
  /** Index = 2 */
  value_type: number;
  /** Index = 3 */
  value_struct_id?: number;
  /** Index = 4 */
  xxx_always_one_4?: number;
  /** Index = 5 */
  xxx_always_one_two_5?: number;
}
export interface TypeDefinition_ServerType {
  /** Index = 1 */
  type_tag: ServerTypeId;
  /** Index = 2 */
  impl: TypeDefinition_ServerType_Implementation;
  /** Index = 100
   *
   * One of the field: schema
   */
  struct_ref?: TypeDefinition_StructReference;
  /** Index = 101
   *
   * One of the field: schema
   */
  map_binding?: TypeDefinition_MapKeyValueBinding;
}
export const TypeDefinition_ServerType_Implementation = {
  PRIMITIVE: 0,
  STRUCT: 1,
  PAIR: 2,
} as const;
export type TypeDefinition_ServerType_Implementation = (typeof TypeDefinition_ServerType_Implementation)[keyof typeof TypeDefinition_ServerType_Implementation];
export interface TypeDefinition_ClientType {
  /** Index = 2 */
  type_tag: ClientTypeId;
  /** Index = 3 */
  impl: TypeDefinition_ClientType_Implementation;
  /** Index = 100
   *
   * One of the field: schema
   */
  struct_ref?: TypeDefinition_StructReference;
  /** Index = 101
   *
   * One of the field: schema
   */
  map_binding?: TypeDefinition_MapKeyValueBinding;
}
export const TypeDefinition_ClientType_Implementation = {
  PRIMITIVE: 0,
  STRUCT: 1,
  PAIR: 2,
} as const;
export type TypeDefinition_ClientType_Implementation = (typeof TypeDefinition_ClientType_Implementation)[keyof typeof TypeDefinition_ClientType_Implementation];
export interface TypedValue {
  /** Index = 1 */
  widget: TypedValue_WidgetType;
  /** Index = 2 */
  is_value_set: number;
  /** Index = 4 */
  type_def?: TypeDefinition;
  /** Index = 3 */
  id_selector?: TypedValue_IdSelector;
  /** Index = 5 */
  tracker?: TypedValue_InstanceTracker;
  /** Index = 101
   *
   * One of the field: storage
   */
  val_id?: Id;
  /** Index = 102
   *
   * One of the field: storage
   */
  val_int?: Int;
  /** Index = 104
   *
   * One of the field: storage
   */
  val_float?: Float;
  /** Index = 105
   *
   * One of the field: storage
   */
  val_string?: String;
  /** Index = 106
   *
   * One of the field: storage
   */
  val_enum?: Enum;
  /** Index = 107
   *
   * One of the field: storage
   */
  val_vector?: Vector;
  /** Index = 108
   *
   * One of the field: storage
   */
  val_struct?: StructStorage;
  /** Index = 109
   *
   * One of the field: storage
   */
  val_list?: ListStorage;
  /** Index = 110
   *
   * One of the field: storage
   */
  val_poly?: PolymorphicValue;
  /** Index = 111
   *
   * One of the field: storage
   */
  val_pair?: MapPairStorage;
  /** Index = 112
   *
   * One of the field: storage
   */
  val_map?: MapStorage;
}
export const TypedValue_WidgetType = {
  UNKNOWN: 0,
  ID_INPUT: 1,
  NUMBER_INPUT: 2,
  DROPDOWN: 3,
  DECIMAL_INPUT: 4,
  TEXT_INPUT: 5,
  ENUM_PICKER: 6,
  VECTOR_GROUP: 7,
  TYPE_SELECTOR: 10000,
  STRUCT_BLOCK: 10001,
  LIST_GROUP: 10002,
  MAP_GROUP: 10003,
  MAP_UNDECIDED: 10006,
  MAP_PAIR_ITEM: 10007,
} as const;
export type TypedValue_WidgetType = (typeof TypedValue_WidgetType)[keyof typeof TypedValue_WidgetType];
export interface TypedValue_IdSelector {
  /** Index = 1 */
  kind: number;
  /** Index = 106
   *
   * One of the field: kind
   */
  status_graph?: TypedValue_IdSelector_Kind;
}
export interface TypedValue_IdSelector_Kind {
  /** Index = 1 */
  selected: number;
}
export interface TypedValue_InstanceTracker {
  /** Index = 1 */
  version_tag: number;
  /** Index = 100 */
  identity: TypedValue_InstanceTracker_Identity;
}
export interface TypedValue_InstanceTracker_Identity {
  /** Index = 1 */
  local_index: number;
}
export interface Id {
  /** Index = 1 */
  id: number;
}
export interface Int {
  /** Index = 1 */
  int: number;
}
export interface Float {
  /** Index = 1 */
  float: number;
}
export interface String {
  /** Index = 1 */
  str: string;
}
export interface Enum {
  /** Index = 1 */
  enum: number;
}
export interface Vector {
  /** Index = 1 */
  vec: Vector_Vec;
}
export interface Vector_Vec {
  /** Index = 1 */
  x: number;
  /** Index = 2 */
  y: number;
  /** Index = 3 */
  z: number;
}
export interface StructStorage {
  /** Index = 1 */
  fields: TypedValue[];
}
export interface ListStorage {
  /** Index = 1 */
  elements: TypedValue[];
}
export interface MapStorage {
  /** Index = 1 */
  pairs: TypedValue[];
}
export interface MapPairStorage {
  /** Index = 1 */
  key: TypedValue;
  /** Index = 2 */
  value: TypedValue;
}
export interface PolymorphicValue {
  /** Index = 1 */
  chosen_type_index: number;
  /** Index = 2 */
  actual_value: TypedValue;
  /** Index = 5 */
  extra_meta?: DynamicTypeMetadata;
}
export interface DynamicTypeMetadata {
  /** Index = 4 */
  version: number;
  /** Index = 100 */
  config: DynamicTypeMetadata_Config;
}
export interface DynamicTypeMetadata_Config {
  /** Index = 1 */
  inner: DynamicTypeMetadata_Config_Inner;
}
export interface DynamicTypeMetadata_Config_Inner {
  /** Index = 1 */
  container_style: TypedValue_WidgetType;
  /** Index = 2 */
  item_style?: TypedValue_WidgetType;
  /** Index = 100
   *
   * One of the field: schema_binding
   */
  target_struct_id?: TypeDefinition_StructReference;
  /** Index = 101
   *
   * One of the field: schema_binding
   */
  list_item_struct_id?: TypeDefinition_StructReference;
  /** Index = 102
   *
   * One of the field: schema_binding
   */
  map_config?: TypeDefinition_MapKeyValueBinding;
  /** Index = 103
   *
   * One of the field: schema_binding
   */
  undecided_map?: TypeDefinition_MapKeyValueBinding;
}
export interface NodeGraphContainer {
  /** Index = 1 */
  inner: NodeGraphContainer_InnerWrapper;
}
export interface NodeGraphContainer_InnerWrapper {
  /** Index = 1 */
  graph: NodeGraph;
}
export interface NodeInterfaceContainer {
  /** Index = 1 */
  inner: NodeInterfaceContainer_InnerWrapper;
}
export interface NodeInterfaceContainer_InnerWrapper {
  /** Index = 1 */
  interface: NodeInterface;
}
export interface StructureDefinitionContainer {
  /** Index = 1 */
  def: StructureDefinition;
}
export interface NodeGraph {
  /** Index = 1 */
  identity: ResourceLocator;
  /** Index = 2 */
  display_name: string;
  /** Index = 3 */
  nodes: NodeInstance[];
  /** Index = 4 */
  port_mappings: InterfaceMapping[];
  /** Index = 5 */
  comments: Annotation[];
  /** Index = 6 */
  blackboard: GraphVariable[];
  /** Index = 100 */
  entry_slot_index?: number;
  /** Index = 101 */
  evaluation_interval?: number;
}
export interface NodeInterface {
  /** Index = 4 */
  id: NodeInterface_Signature;
  /** Index = 100 */
  inflows: PinInterface[];
  /** Index = 101 */
  outflows: PinInterface[];
  /** Index = 102 */
  inputs: PinInterface[];
  /** Index = 103 */
  outputs: PinInterface[];
  /** Index = 106 */
  meta_pins: PinInterface[];
  /** Index = 107 */
  impl: NodeInterface_Implementation;
  /** Index = 200 */
  name: string;
  /** Index = 201 */
  description: string;
  /** Index = 203 */
  template_root: NodeInterface_TemplateRoot;
  /** Index = 204 */
  template_sub: NodeInterface_TemplateSub;
}
export interface NodeInterface_Signature {
  /** Index = 1 */
  shell_ref: ResourceLocator;
  /** Index = 2 */
  kernel_ref: ResourceLocator;
  /** Index = 4 */
  graph_ref: ResourceLocator;
  /** Index = 5 */
  signal_version?: number;
}
export interface NodeInterface_Implementation {
  /** Index = 1 */
  category: NodeInterface_Implementation_Category;
  /** Index = 101
   *
   * One of the field: template
   */
  send_signal?: SignalSignature;
  /** Index = 102
   *
   * One of the field: template
   */
  listen_signal?: SignalSignature;
  /** Index = 104
   *
   * One of the field: template
   */
  assemble_struct?: NodeInterface_Implementation_Id;
  /** Index = 105
   *
   * One of the field: template
   */
  split_struct?: NodeInterface_Implementation_Id;
  /** Index = 106
   *
   * One of the field: template
   */
  modify_struct?: NodeInterface_Implementation_Id;
}
export const NodeInterface_Implementation_Category = {
  UNKNOWN: 0,
  COMPOSITE: 1000,
  SEND_SIGNAL: 1001,
  LISTEN_SIGNAL: 1002,
  STRUCT_ASSEMBLY: 1003,
  STRUCT_SPLIT: 1004,
  STRUCT_MODIFY: 1005,
} as const;
export type NodeInterface_Implementation_Category = (typeof NodeInterface_Implementation_Category)[keyof typeof NodeInterface_Implementation_Category];
export interface NodeInterface_Implementation_Id {
  /** Index = 1 */
  id: number;
}
export const NodeInterface_TemplateRoot = {
  UNKNOWN: 0,
  SUB_TEMPLATE: 1,
  LISTEN_SIGNAL: 2,
  STRUCT: 5,
  USER_COMPOSITE: 6,
} as const;
export type NodeInterface_TemplateRoot = (typeof NodeInterface_TemplateRoot)[keyof typeof NodeInterface_TemplateRoot];
export const NodeInterface_TemplateSub = {
  NONE: 0,
  MODIFY_STRUCT: 3,
  STRUCT_SUB: 4,
  SIGNAL_SUB: 8,
} as const;
export type NodeInterface_TemplateSub = (typeof NodeInterface_TemplateSub)[keyof typeof NodeInterface_TemplateSub];
export interface PinInterface {
  /** Index = 1 */
  name: string;
  /** Index = 2 */
  visibility_mask: number;
  /** Index = 3 */
  sig: PinSignature;
  /** Index = 4 */
  type: PinInterface_TypeInfo;
  /** Index = 5 */
  meta_sig_type?: PinSignature;
  /** Index = 8 */
  persistent_pin_uid: number;
}
export interface PinInterface_TypeInfo {
  /** Index = 1 */
  ui_class?: TypedValue_WidgetType;
  /** Index = 3 */
  var_type_shell?: ServerTypeId;
  /** Index = 4 */
  var_type_kernel?: ServerTypeId;
  /** Index = 5 */
  placeholder?: PinInterface_TypeInfo_Placeholder;
  /** Index = 7 */
  display_state?: PinInterface_TypeInfo_DisplayState;
  /** Index = 101
   *
   * One of the field: detail
   */
  enum_id?: PinInterface_TypeInfo_EnumId;
  /** Index = 102
   *
   * One of the field: detail
   */
  list_item_type?: PinInterface_TypeInfo_ListType;
  /** Index = 104
   *
   * One of the field: detail
   */
  struct_id?: PinInterface_TypeInfo_StructId;
  /** Index = 105
   *
   * One of the field: detail
   */
  map_type?: PinInterface_TypeInfo_MapType;
}
export interface PinInterface_TypeInfo_Placeholder {
  /** Index = 1 */
  always_1: number;
  /** Index = 2 */
  text: string;
}
export interface PinInterface_TypeInfo_DisplayState {
  /** Index = 1 */
  state: PinInterface_TypeInfo_DisplayState_State;
}
export const PinInterface_TypeInfo_DisplayState_State = {
  NONE: 0,
  SIGNAL_NAME: 4,
} as const;
export type PinInterface_TypeInfo_DisplayState_State = (typeof PinInterface_TypeInfo_DisplayState_State)[keyof typeof PinInterface_TypeInfo_DisplayState_State];
export interface PinInterface_TypeInfo_EnumId {
  /** Index = 1 */
  val: number;
}
export interface PinInterface_TypeInfo_ListType {
  /** Index = 1 */
  item_type: PinInterface_TypeInfo;
}
export interface PinInterface_TypeInfo_StructId {
  /** Index = 2 */
  val: number;
}
export interface PinInterface_TypeInfo_MapType {
  /** Index = 3 */
  key: ServerTypeId;
  /** Index = 4 */
  value: ServerTypeId;
  /** Index = 5 */
  struct_id?: number;
}
export interface StructureDefinition {
  /** Index = 1 */
  genericField: StructureDefinition_Field;
  /** Index = 2 */
  concreteField: StructureDefinition_Field;
  /** Index = 3 */
  structVersion: number;
  /** Index = 4 */
  itemCount: number;
  /** Index = 5 */
  xxx_always_one_5: number;
}
export interface StructureDefinition_Field {
  /** Index = 1 */
  id: number;
  /** Index = 2 */
  xxx: number;
  /** Index = 3 */
  vars: StructureDefinition_VarDef[];
  /** Index = 501 */
  structName: string;
  /** Index = 502 */
  classBase: number;
  /** Index = 503 */
  index: number;
}
export interface StructureDefinition_VarDef {
  /** Index = 1 */
  generic_def: StructureDefinition_VarDef_GenericDef;
  /** Index = 3 */
  kernel_def: StructureDefinition_VarDef_KernelDef;
  /** Index = 5 */
  name: string;
  /** Index = 501 */
  varName: string;
  /** Index = 502 */
  varType: ServerTypeId;
  /** Index = 503 */
  varIndex: number;
}
export interface StructureDefinition_VarDef_StructureInfo {
  /** Index = 1 */
  has_structure_info: boolean;
  /** Index = 2 */
  runtime_id: number;
  /** Index = 502 */
  key_type: ServerTypeId;
  /** Index = 503 */
  value_type: ServerTypeId;
  /** Index = 504 */
  value_struct_id: number;
}
export interface StructureDefinition_VarDef_GenericDef {
  /** Index = 1 */
  type: ServerTypeId;
  /** Index = 2 */
  structure_info: StructureDefinition_VarDef_StructureInfo;
}
export interface StructureDefinition_VarDef_KernelDef {
  /** Index = 1 */
  type: ServerTypeId;
  /** Index = 2 */
  generic_def: StructureDefinition_VarDef_GenericDef;
  /** Index = 11
   *
   * One of the field: val
   */
  val_entity?: StructureDefinition_VarDef_KernelDef_Id;
  /** Index = 12
   *
   * One of the field: val
   */
  val_id?: StructureDefinition_VarDef_KernelDef_Id;
  /** Index = 13
   *
   * One of the field: val
   */
  val_int?: StructureDefinition_VarDef_KernelDef_Int;
  /** Index = 14
   *
   * One of the field: val
   */
  val_enum?: Enum;
  /** Index = 15
   *
   * One of the field: val
   */
  val_float?: StructureDefinition_VarDef_KernelDef_Float;
  /** Index = 16
   *
   * One of the field: val
   */
  val_string?: StructureDefinition_VarDef_KernelDef_String;
  /** Index = 17
   *
   * One of the field: val
   */
  val_idList?: StructureDefinition_VarDef_KernelDef_Id;
  /** Index = 18
   *
   * One of the field: val
   */
  val_intList?: StructureDefinition_VarDef_KernelDef_IntList;
  /** Index = 19
   *
   * One of the field: val
   */
  val_enumList?: StructureDefinition_VarDef_KernelDef_IdList;
  /** Index = 20
   *
   * One of the field: val
   */
  val_floatList?: StructureDefinition_VarDef_KernelDef_FloatList;
  /** Index = 21
   *
   * One of the field: val
   */
  val_stringList?: StructureDefinition_VarDef_KernelDef_StringList;
  /** Index = 22
   *
   * One of the field: val
   */
  val_vector?: StructureDefinition_VarDef_KernelDef_Vector;
  /** Index = 23
   *
   * One of the field: val
   */
  val_entityList?: StructureDefinition_VarDef_KernelDef_IdList;
  /** Index = 25
   *
   * One of the field: val
   */
  val_vectorList?: StructureDefinition_VarDef_KernelDef_VectorList;
  /** Index = 27
   *
   * One of the field: val
   */
  val_faction?: StructureDefinition_VarDef_KernelDef_IdList;
  /** Index = 30
   *
   * One of the field: val
   */
  val_config?: StructureDefinition_VarDef_KernelDef_Prefab;
  /** Index = 31
   *
   * One of the field: val
   */
  val_prefab?: StructureDefinition_VarDef_KernelDef_Prefab;
  /** Index = 32
   *
   * One of the field: val
   */
  val_configList?: StructureDefinition_VarDef_KernelDef_PrefabList;
  /** Index = 33
   *
   * One of the field: val
   */
  val_prefabList?: StructureDefinition_VarDef_KernelDef_PrefabList;
  /** Index = 34
   *
   * One of the field: val
   */
  val_factionList?: StructureDefinition_VarDef_KernelDef_IdList;
  /** Index = 35
   *
   * One of the field: val
   */
  val_entry?: StructureDefinition_VarDef_KernelDef_Entry;
  /** Index = 36
   *
   * One of the field: val
   */
  val_structList?: StructureDefinition_VarDef_KernelDef_Entry;
  /** Index = 37
   *
   * One of the field: val
   */
  val_dict?: StructureDefinition_VarDef_KernelDef_Dict;
  /** Index = 501 */
  varName: string;
}
export interface StructureDefinition_VarDef_KernelDef_Id {
  /** Index = 1 */
  id: number;
}
export interface StructureDefinition_VarDef_KernelDef_IdList {
  /** Index = 1 */
  id: number[];
}
export interface StructureDefinition_VarDef_KernelDef_Prefab {
  /** Index = 1 */
  inner: StructureDefinition_VarDef_KernelDef_Prefab_PrefabInner;
}
export interface StructureDefinition_VarDef_KernelDef_Prefab_PrefabInner {
  /** Index = 2 */
  ref_id: number;
}
export interface StructureDefinition_VarDef_KernelDef_PrefabList {
  /** Index = 1 */
  inner: StructureDefinition_VarDef_KernelDef_PrefabList_PrefabInner[];
}
export interface StructureDefinition_VarDef_KernelDef_PrefabList_PrefabInner {
  /** Index = 2 */
  ref_id: number;
}
export interface StructureDefinition_VarDef_KernelDef_Int {
  /** Index = 1 */
  int: number;
}
export interface StructureDefinition_VarDef_KernelDef_IntList {
  /** Index = 1 */
  int: number[];
}
export interface StructureDefinition_VarDef_KernelDef_Float {
  /** Index = 1 */
  float: number;
}
export interface StructureDefinition_VarDef_KernelDef_FloatList {
  /** Index = 1 */
  float: number[];
}
export interface StructureDefinition_VarDef_KernelDef_String {
  /** Index = 1 */
  str: string;
}
export interface StructureDefinition_VarDef_KernelDef_StringList {
  /** Index = 1 */
  str: string[];
}
export interface StructureDefinition_VarDef_KernelDef_Vector {
  /** Index = 1 */
  vec: StructureDefinition_VarDef_KernelDef_Vector_Vec;
}
export interface StructureDefinition_VarDef_KernelDef_Vector_Vec {
  /** Index = 1 */
  x: number;
  /** Index = 2 */
  y: number;
  /** Index = 3 */
  z: number;
}
export interface StructureDefinition_VarDef_KernelDef_VectorList {
  /** Index = 1 */
  vec: StructureDefinition_VarDef_KernelDef_VectorList_Vec[];
}
export interface StructureDefinition_VarDef_KernelDef_VectorList_Vec {
  /** Index = 1 */
  x: number;
  /** Index = 2 */
  y: number;
  /** Index = 3 */
  z: number;
}
export interface StructureDefinition_VarDef_KernelDef_Entry {
  /** Index = 1 */
  elem: StructureDefinition_VarDef_KernelDef[];
  /** Index = 501 */
  runtime_id: number;
  /** Index = 502 */
  reference: ResourceLocator;
}
export interface StructureDefinition_VarDef_KernelDef_Dict {
  /** Index = 1 */
  elem: StructureDefinition_VarDef_KernelDef[];
  /** Index = 501 */
  keys: StructureDefinition_VarDef_KernelDef;
  /** Index = 502 */
  values: StructureDefinition_VarDef_KernelDef;
  /** Index = 503 */
  key_type: ServerTypeId;
  /** Index = 504 */
  value_type: ServerTypeId;
  /** Index = 505 */
  value_struct_id: number;
}
export interface NodeInstance {
  /** Index = 1 */
  index: number;
  /** Index = 2 */
  shell_ref: ResourceLocator;
  /** Index = 3 */
  kernel_ref?: ResourceLocator;
  /** Index = 4 */
  pins: PinInstance[];
  /** Index = 5 */
  x_pos: number;
  /** Index = 6 */
  y_pos: number;
  /** Index = 7 */
  attached_comment?: Annotation;
  /** Index = 8 */
  context_declaration?: PinSignature;
  /** Index = 9 */
  signal_version?: number;
  /** Index = 10 */
  using_structs: NodeInstance_DependencyDeclaration[];
  /** Index = 11 */
  execution_sequence?: NodeInstance_CreationExecSeq;
}
export interface NodeInstance_DependencyDeclaration {
  /** Index = 1 */
  identity: ResourceLocator;
}
export interface NodeInstance_CreationExecSeq {
  /** Index = 1 */
  class_base: number;
  /** Index = 100
   *
   * One of the field: class
   */
  sequence_length?: NodeInstance_CreationExecSeq_SequenceLen;
}
export interface NodeInstance_CreationExecSeq_SequenceLen {
  /** Index = 1 */
  len: number;
}
export interface PinSignature {
  /** Index = 1 */
  kind: PinSignature_Kind;
  /** Index = 2 */
  index: number;
  /** Index = 100 */
  source_ref?: PinSignature_SignalId;
}
export const PinSignature_Kind = {
  UNKNOWN: 0,
  IN_FLOW: 1,
  OUT_FLOW: 2,
  IN_PARAM: 3,
  OUT_PARAM: 4,
  META_RPC_OPCODE: 5,
  META_TOPIC_NAME: 6,
  STRUCT_REF: 13,
  STRUCT_KEY_MOD: 14,
  STRUCT_KEY_SET: 15,
  STRUCT_KEY_SELECT: 16,
} as const;
export type PinSignature_Kind = (typeof PinSignature_Kind)[keyof typeof PinSignature_Kind];
export interface PinSignature_SignalId {
  /** Index = 1 */
  id: number;
}
export interface SignalSignature {
  /** Index = 1 */
  signal_name: string;
  /** Index = 2 */
  server_node_id: ResourceLocator;
  /** Index = 3 */
  client_node_id: ResourceLocator;
}
export interface PinInstance {
  /** Index = 1 */
  shell_sig: PinSignature;
  /** Index = 2 */
  kernel_sig: PinSignature;
  /** Index = 3 */
  value: TypedValue;
  /** Index = 4 */
  type: number;
  /** Index = 5 */
  connections: NodeConnection[];
  /** Index = 6 */
  binding_meta?: PinSignature;
  /** Index = 7 */
  persistent_pin_uid?: number;
}
export interface NodeConnection {
  /** Index = 1 */
  target_node_index: number;
  /** Index = 2 */
  target_pin_shell: PinSignature;
  /** Index = 3 */
  target_pin_kernel: PinSignature;
}
export interface InterfaceMapping {
  /** Index = 1 */
  external_port: PinSignature;
  /** Index = 2 */
  internal_target_node_handle: number;
  /** Index = 3 */
  internal_port_shell: PinSignature;
  /** Index = 4 */
  internal_port_kernel: PinSignature;
}
export interface GraphVariable {
  /** Index = 2 */
  var_name: string;
  /** Index = 3 */
  base_type: ServerTypeId;
  /** Index = 4 */
  storage_value: TypedValue;
  /** Index = 5 */
  is_public: boolean;
  /** Index = 6 */
  schema_ref_id?: number;
  /** Index = 7 */
  container_key_type: ServerTypeId;
  /** Index = 8 */
  container_value_type: ServerTypeId;
}
export interface Annotation {
  /** Index = 1 */
  text: string;
  /** Index = 2 */
  x_pos?: number;
  /** Index = 3 */
  y_pos?: number;
}
export interface LevelNodeGraphContainer {
  /** Index = 1 */
  inner: LevelNodeGraphContainer_NodeGraphWrapper[];
  /** Index = 2 */
  generated_nodes: LevelNodeGraphContainer_NodeWrapper[];
  /** Index = 4 */
  composite_graphs: LevelNodeGraphContainer_NodeGraphWrapper[];
  /** Index = 6 */
  structure_definitions: StructureDefinition[];
}
export interface LevelNodeGraphContainer_NodeGraphWrapper {
  /** Index = 1 */
  graph: NodeGraph;
}
export interface LevelNodeGraphContainer_NodeWrapper {
  /** Index = 1 */
  node: NodeInterface;
}
export interface Level {
  /** Index = 2 */
  level_name: string;
  /** Index = 10 */
  graph_data: LevelNodeGraphContainer;
  /** Index = 43 */
  engine_version: string;
}
